### ISSUE TITLE
Regression: when using 'Export selected only' objects which are linked / children of other objects are not exported

### ISSUE THREAD

**Issue by leoncvlt** [BabylonJS/Exporters#1008]
3DS Max version: 2020.3.2
Exporter version: v20210811.2

As the title says, I'm talking about the "[Select and link](https://knowledge.autodesk.com/support/3ds-max/learn-explore/caas/CloudHelp/cloudhelp/2020/ENU/3DSMax-Animation/files/GUID-D5446135-7734-4F9A-A1A1-3564FB89147B-htm.html)" functionality.

![image](https://user-images.githubusercontent.com/4929974/136249014-ea09b3cd-3d0c-4414-b26c-55dc98669464.png)

Attaching a 3ds max 2020 scene file to replicate the issue:
[bug.zip](https://github.com/BabylonJS/Exporters/files/7295847/bug.zip)

When "Export only selected" is toggled, Box001 will export fine, but Box002 will effectively export no meshes:
![image](https://user-images.githubusercontent.com/4929974/136249728-d805211f-92d4-493b-862e-5d44c0d3fca0.png)

Break the relationship using the "Unlink selection" button (next to select and link) and Box002 will export fine.

Raising this as a regression because I've always been using this workflow (linking multiple object under one dummy box gizmo) and it has always been working fine until I updated to 20210811.2, not sure which version the regression was introduced in.

**Comment by pandaGaume** [comment]
Hello,
The change is coming from the way we initialize now the scene using the Max API to get **all** the object or only the **selected** (by passing a boolean [here](https://github.com/BabylonJS/Exporters/blob/598ff9763d7e2f26f50b6071b14d0879a730e50b/3ds%20Max/Max2Babylon/Exporter/BabylonExporter.cs#L294)) to be loaded into the SDK. This is a real optimization when we manage complex scenes, but it's seem it's break the hierarchy, because the API did not return the child after that. Let me discuss this topic with the team.

**Comment by leoncvlt** [comment]
Thanks for the fix!
