### ISSUE TITLE
Cannot export animation keyframes that are targeting morph modifier in 3DS Max

### ISSUE THREAD

**Issue by yaserOSource** [BabylonJS/Exporters#1013]
Models that have morph targets can be exported out with babylonjs exporter but the animation keyframes do not get exported out.

Is this a known issue?

**Comment by yaserOSource** [comment]
So if you modify the animation it works? But only if you do it by hand via the babylon file directly? Is there anything that can be done on the 3ds max side to fix this? Or on the exporter itself?

I also noticed that the animation key was called influence animation, usually i only see 'visibility animation'. Was this due to the id change and the reference?

**Comment by pandaGaume** [comment]
Hey,
The generated Babylon seem totally legit, but the Babylon sandbox is not displaying animation in the case of no animation group.
The morph animation is well saved into the morph target. I asked the team to have a look on the file to back me up. @bghgary did you send the file to the team for review??
Then finally the issue is more about how to specify an animation group targeting a deleted morph target...
But if you intend to use the file as it, you can use the morph programatically or by a different path into the sandbox
![image](https://user-images.githubusercontent.com/22658224/140407952-a283fa27-b9e8-4bd3-91dc-869b4db6bb66.png)

**Comment by yaserOSource** [comment]
Hi @pandaGaume 
Thanks for your response. The biggest issue is not being able to use the animation clips with the morph targets, because we will have many animations that go through each of the morph targets 1 by 1, playing the change in the target slider. 

So i load the mesh with the morph targets, and then i want to load the animations and play them 1 by 1
