### ISSUE TITLE
Make sure gltf node names are unique

### ISSUE THREAD

**Issue by deltakosh** [BabylonJS/Exporters#135]

**Comment by noalak** [comment]
Unique node names for Maya not done since only relevant for animations (will do it at this time).

**Comment by Selmar** [comment]
This feature is actually unwanted for us. Looking at the code, it doesn't seem necessary.

If a renderer relies on unique names, then I think that's a problem with that renderer. The specification explicitly states that a name does not have to be unique. I think, if anything, this should be an option that is by default `false`.

**Comment by tkazik** [comment]
interesting WIP:

https://github.com/KhronosGroup/glTF-Validator/issues/93

**Comment by donmccurdy** [comment]
> This feature is actually unwanted for us.

@Selmar could you clarify why you might want duplicate names? E.g. are you using the name to represent some data about the object? Or it makes the modeling workflow inconvenient?

**Comment by Selmar** [comment]
Yes, we use some naming conventions for certain types of nodes / meshes / lights. We link to those objects by name in other files.

Our problem comes mainly from the fact that we hash the name strings (for performance reasons), which makes it impossible to search for partial names.

I also see advantages to having unique names, though, it makes it impossible for artists to mix things up. 

However, in this case it's enforced only on export, so we find out afterwards and end up wasting time (because the artist does not always look at the output, or perhaps doesn't even know which names are important).

**Comment by deltakosh** [comment]
Could you use the tags now that we added them for your needs?

**Comment by Selmar** [comment]
Tags are for `.babylon` only, aren't they? It's not so difficult to add an extension to gltf, of course.

For now, we are aware of it, so it's not the biggest problem.

**Comment by deltakosh** [comment]
We will add tags to extra field in gltf node as well

**Comment by donmccurdy** [comment]
The [glTF `.extras`](https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/README.md#reference-extras) field is used our engine too, I think that would be a good option. 👍
