### ISSUE TITLE
[3dsMax][glTF] Model of RiggedFigure exported with 3ds Max is incorrect

### ISSUE THREAD

**Issue by cx20** [BabylonJS/Exporters#170]
I tried to display the following model with [online viewer](https://sandbox.babylonjs.com/).
https://github.com/BabylonJS/Exporters/tree/master/3ds%20Max/Samples/glTF%202.0/RiggedFigure

[Babylon.js Viewer (v3.2.0-rc.4) + RiggedFigure.gltf result:](https://sandbox.babylonjs.com/)
![riggedfigure_max_export](https://user-images.githubusercontent.com/1833979/39472568-299e6fa2-4d85-11e8-9f2f-bf2258a034a2.gif)

I did not actually convert it because I do not have 3ds Max, but probably there is a problem in the conversion result.

**Comment by noalak** [comment]
Hi,

What's the issue exactly ?

The right hand is intentionally not animated in order to check if the result is mirrored or not.

The head is spinning in an unnatural way just like in 3ds Max / Maya.
After checking, the gltf result provided by Khronos Group is actually not the same. The head is nodding instead.
Either the source file (.dae) is incorrect or the import into 3ds max is bugged.

**Comment by cx20** [comment]
> What's the issue exactly ?

I assumed that it would simply be the same result as the [glTF model](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/RiggedFigure) of Khronos's [glTF-Sample-Models](https://github.com/KhronosGroup/glTF-Sample-Models) repository.

However, if the head is spinning in an unnatural in 3ds Max / Maya, there seems to be a problem with the import processing, not the exporter.

**Comment by deltakosh** [comment]
Confirmed!
Closing this one then :)
Thanks!
