### ISSUE TITLE
Create a maya importer for glTF

### ISSUE THREAD

**Issue by deltakosh** [BabylonJS/Exporters#184]

**Comment by deltakosh** [comment]
We do not plan to support it for now

**Comment by Drigax** [comment]
Yeah, we should have an importer to pair with our exporters. Unfortunately I don't see myself being able to dedicate a significant amount of time to this for the next few months due to its complexity and scope. But I hope to eventually get to it, but if anyone thinks that they can do it now, feel free :).

**Comment by sebavan** [comment]
Closed as grouped with #428 to share as much as we can during the dev.
