### ISSUE TITLE
Crash on export 3ds Max 2018.4 tested on Max2Babylon 1.0.5

### ISSUE THREAD

**Issue by Gil-1** [BabylonJS/Exporters#189]
Hello,

The following scene is causing a crash everytime we export it.
The "Retina" mesh is causing the crash because of some settings / links in the Morpher Modifier I suppose.

Doing an export selected by selecting another mesh is also causing a crash.
The fact that the mesh is in the scene make it crash.

[Morpher_Crash.zip](https://github.com/BabylonJS/Exporters/files/2026252/Morpher_Crash.zip)

I enclosed a simple scene to help debug it.
Let me know if I can help further.

**Comment by noalak** [comment]
Hi Gil-1,

Bug not reproduced with 2018.0
I get Update 4 and go back to you soon

Some questions:
1. Are you exporting to babylon or glTF format ?
2. The crash occurs while exporting or when loading the output scene inside an engine ?

**Comment by Gil-1** [comment]
I'm exporting in babylon format and the crash occurs while exporting. I have the green bar moving to something like 10% then Max crashes.

Thanks for testing :)

**Comment by Jaskar** [comment]
We got the updates today, @noalak will test it next week.

**Comment by noalak** [comment]
Using the complete scene, I found that:
- by creating copies of the targets and assigning those copies as targets instead of the original ones, then the export is fine.
- when creating a copy of the 'Glaucoma_halfeye_morph_retina' mesh, the number of vertices of the cloned mesh displayed is 3 and the Vertex Selection Tool is not active.

My guess is that file corrupted in some way.
As said, there is nothing we can do to prevent or warn that from the exporter side.
Maybe the Autodesk staff can help you.
