### ISSUE TITLE
Camera, lighting and visibility export?

### ISSUE THREAD

**Issue by jdswiney** [BabylonJS/Exporters#249]
They all work great when exporting to Babylon.js files. Thanks for adding them! When exporting to GLTF files, the camera, lighting and visibility doesn't seem to work. It would be awesome to have them there too. Is a limitation of the GLTF file type?

**Comment by deltakosh** [comment]
Camera are not exported yet to gltf.
Lighting should work soon (we are working on supporting khr_lights extension for gltf)

Visibility is not part of gltf spec

**Comment by deltakosh** [comment]
Pinging @noalak for confirmation

**Comment by noalak** [comment]
Cameras are exported in glTF. However, glTF specs only defines free cameras. Cameras with aim (ArcRotateCamera) are not supported by glTF specs.
Because of that, in the Babylon Sandbox, an ArcRotateCamera is always created and used by default to ease visualisation of the scene. You can switch between cameras using the Inspector panel (square with pen icon on the bottom right corner).

Lights are exported using KHR_lights extension. This extension is optional. Babylon does read it. Make sure your engine does too.

As you said, visibility is not part of gltf spec.

Btw, which software are you exporting from ? 3ds max, Maya, Unity ?

**Comment by jdswiney** [comment]
Thank you for the info. I will probably be sticking with the Bablyon.js files because visibility is an important feature for what I plan on doing.  I am using Maya 2018.2  Please forgive my ignorance on the coding aspects when I make requests or comments. I am an animator and not a coder. I am trying to learn as much as I can.

**Comment by deltakosh** [comment]
No problem at ALL. You are more than welcome to ask questions
I also recommend using our forum because we have a really great community always willing to help:
http://www.html5gamedevs.com/forum/16-babylonjs/
