### ISSUE TITLE
3d max exporer instance pickable properties   can't work

### ISSUE THREAD

**Issue by QilongLiao** [BabylonJS/Exporters#290]
3d max exporer instance pickable value always is true. 
instance pickable value  can't work

**Comment by sebavan** [comment]
Hello,

Is it possible to have a bit more information ? or the way to repro.

**Comment by QilongLiao** [comment]
Exporter babylon file instanes properties  like below, 
exporter instances don't have"isPickable" property.  on scene "isPickable" default value is true
` "instances": [{
            "rotation": [0.0, 0.0, 0.0],
            "scaling": [1.0, 1.0, 1.0],
            "rotationQuaternion": [0.0, 0.0, 0.0, 1.0],
            "actions": null,
            "name": "Box002",
            "id": "0fe809e3-f772-4577-8fb4-1c7b018ecb43",
            "parentId": null,
            "position": [-85.3081, 9.1433, 19.1153],
            "animations": [],
            "autoAnimate": true,
            "autoAnimateFrom": 0,
            "autoAnimateTo": 100,
            "autoAnimateLoop": true
        }`

**Comment by sebavan** [comment]
Thx, I ll try to see if I can find smthg obvious, else this might have to wait a bit as our importers gurus are in vacation :-)

**Comment by noalak** [comment]
Hi,

In a nutshell, there is some confusion on which property should be defined at abstract mesh level or at mesh level.

@sebavan About the Babylon engine, do we want the isPickable property to be set per instance ? Or only for the master mesh ?
According to the class hierarchy of the engine, the isPickable property is defined at BABYLON.AbstractMesh level which implies that each instance can have its own value of isPickable.
However, the loader (BABYLON.Mesh.Parse method) does not update the isPickable value for instances, letting them at their default value, which is 'true'.

Additionally, for the exporter, the isPickable property can be set for each instance through the 'Object Properties' window but the value is ignored and only the master mesh property is exported. This is something to fix one way or another, depending on Sebavan answer.

Other properties are also concerned by those issues. Looking only at the exported ones from 3ds Max:

![qilongliao](https://user-images.githubusercontent.com/20560340/44081228-86d8c67e-9fae-11e8-86ea-7b0a076f6a6f.png)

Animations are a special case. They are initialized in the engine when loading but using the master mesh values instead of the instance ones. @sebavan Is this intended ?

**Comment by sebavan** [comment]
This is a pretty valid question :-)

We ll check with @deltakosh soon and come back to the thread.

My rough guess is that everything is currently mesh focused despite the will to use them with instances.

**Comment by deltakosh** [comment]
We should just consider instances like regular meshes (and then update the loader)
So IsPickable, collisions, etc.. should also be on the instances
