### ISSUE TITLE
[3ds Max] KHR_materials_unlit support

### ISSUE THREAD

**Issue by johanos** [BabylonJS/Exporters#292]
https://github.com/KhronosGroup/glTF/tree/master/extensions/2.0/Khronos/KHR_materials_unlit

**Comment by johanos** [comment]
Hey guys, 

Do you support, or plan to support the KHR_materials_unlit extension?

**Comment by sebavan** [comment]
This is already supported in BabylonJS so if your gltf/glb are flagged as unlit this would work but unfrotunately it is part of the exporters so far.

It looks like a good idea, let me add @noalak and @Jaskar to the thread.

**Comment by johanos** [comment]
Yeah definitely, my use case is that i am generating a shadow plane texture to aid in realism and cut down on render load. but the plane is coming out shiny unless I add unlit manually. would rather have it use the spec to set it.

**Comment by noalak** [comment]
Hi,

Adding the KHR_materials_unlit extension to a material in the exported file is very easy.

The issue I have with this is the UI.
Do you want all materials to have the same value of unlit ? In this case it's simple to add a checkbox in the scene properties.
Alternatively, do you want to specify the unlit property per material ? In this case, ideally you would want a checkbox in the material window, like this
![khr_materials_unlit_customattributes](https://user-images.githubusercontent.com/20560340/44098736-42603044-9fe1-11e8-90d9-87f33cf2536d.png)
This property would change nothing in 3ds max (viewport or renderer) but will add the extension if checked.
For now, I've not achieved to add this property for all materials by default. I need to run a script first to add the Unlit attribute to all materials.

Anyway before going any further, what are your thoughts ?

**Comment by sebavan** [comment]
Per material would be amazing as it is often the case in a scene/model where materials are mixed.

I guess the 3dsmax limitation is totally understandable and acceptable.

**Comment by noalak** [comment]
Hi johanos,

Exporter [Max2Babylon-1.2.26.zip](https://github.com/BabylonJS/Exporters/files/2303071/Max2Babylon-1.2.26.zip) adds the KHR_materials_unlit extension to materials with the Unlit attribute checked.

[This MaxScript](https://github.com/BabylonJS/Exporters/files/2303068/BabylonMaterialAttributes.zip) add the Unlit attribute to all materials assigned in the scene (default unchecked). This results in the material editor view above.

Note that this script simply adds a new [custom attribute](https://knowledge.autodesk.com/support/3ds-max/learn-explore/caas/CloudHelp/cloudhelp/2016/ENU/3DSMax/files/GUID-7EAA7D84-5775-4E4C-9936-D874EB7A42BB-htm.html) under a Babylon Attributes roller. You can add the attribute manually instead of using this script if you will. Just be sure to name it 'babylonUnlit' (internal use) and not 'Unlit' (display use).

Is this solution ok for you ?

**Comment by sebavan** [comment]
Thx, the PR has been merged i ll close the issue after getting the feedback :-)

**Comment by sebavan** [comment]
Closing for now, will create new ones for follow up if needed.
