### ISSUE TITLE
[3dsmax] Exporter not respecting levels set for maps

### ISSUE THREAD

**Issue by johanos** [BabylonJS/Exporters#311]
Hey guys. is it intended that the exporter doesn't take into account map levels for things like a bump texture.. 

I've attached a max file that shows what i mean. the bump map from the exporter gets put at an intensity of 100% instead of 10% so then it becomes way to strong. 

![image](https://user-images.githubusercontent.com/6535806/44924415-3765b480-ad19-11e8-8bcf-5ebea35c2fe5.png)

this is what the model is supposed to look like 
(normal map at 10%)
![image](https://user-images.githubusercontent.com/6535806/44924524-8f9cb680-ad19-11e8-952e-ccf7cfbb7eb6.png)

but this is what is outputted (normal map at 100%)

![image](https://user-images.githubusercontent.com/6535806/44924571-b0650c00-ad19-11e8-856f-613824f068cb.png)

I think this should be something that the exporter can handle, in the mean time one has to manually change the maps so things come out correctly. 

[MicroSample.zip](https://github.com/BabylonJS/Exporters/files/2340865/MicroSample.zip)

**Comment by johanos** [comment]
Looking at this more it might be because it is a grey scale bump map as well as the level. It might be beneficial to have this tool try to make a normal map from bump maps kind of like in this article. In addition to respecting the levels

http://flexmonkey.blogspot.com/2016/04/creating-procedural-normal-maps-for.html

**Comment by deltakosh** [comment]
Well the goal of the exporter is not to work on textures on behalf of the artist. The bump map must be a normal map.
The level should be exported though

**Comment by noalak** [comment]
Map level is exported in babylon but not in gltf because such attribute doesn't exist in gltf specs.
This means that textures must be treated by the exporter when the level is not 1.

Pros:
- Automatic treatment, nothing to do for the graphist

Cons:
- The treatment would be done every export
- The compression/format would be dictated by the exporter

@deltakosh Your thoughts ?

**Comment by Selmar** [comment]
@noalak Could this be similar enough to the `normalTextureInfo.scale` property?

**Comment by deltakosh** [comment]
I'm not for updating the textures because of your cons list actually
But as Selmar mentioned perhaps we can map these levels to some factor values?

**Comment by deltakosh** [comment]
@kcoley can you have a look wehn you have a chance?

**Comment by kcoley** [comment]
Sure thing, I will look into @Selmar 's suggestion

**Comment by kcoley** [comment]
@johanos checking out the scene, it looks like you are not using a tangent space normal map which will cause rendering problems when exporting to glTF since it only sees data in one channel where it is expecting normal components in R, G and B, which you alluded to.  Converting to a tangent-space normal map solve the initial problem.  There is a blog post on the Khronos blog which goes over the glTF workflow for various DCC tools, including 3ds Max: https://www.khronos.org/blog/art-pipeline-for-gltf

As for `level`, I believe it can be mapped to the `normalTextureInfo.scale` parameter, though 'scale' would have to be added to the exporter.  I'll work on adding that.

**Comment by kcoley** [comment]
@johanos I also noticed that you are not using the physical material, which already supports using the level for the bump map according to the docs: https://doc.babylonjs.com/resources/3dsmax_to_gltf

Can you try switching over to using a physical material and see if the scale is applied as expected?

**Comment by johanos** [comment]
I'll try that now. the glb's I end up with should all be converted to Physical materials. but maybe there's a bug in my scripts. that saved file is from a step in a maxscript pipeline. 

I found that its not that hard to convert a bump map to a normal map using max's internal tools so anyone can implement a script for it.

**Comment by deltakosh** [comment]
Closing for now

**Comment by ogmasoul3d** [comment]
Hi, I hope I am doing something wrong.. but I cannot get the Bump map weight param from the Physical Material in max 2019 to do anything to the normalTexture scale parameter on export.
![normalTextureScale-bug](https://user-images.githubusercontent.com/136207/82835879-95f79c80-9ec5-11ea-9f26-f5ec3668e321.jpg)

From what I can see I never get that parameter written in the gltf file?
![normalTextureScale-bug_p2](https://user-images.githubusercontent.com/136207/82836359-a8260a80-9ec6-11ea-93d4-a50608d66776.jpg)
