### ISSUE TITLE
Max2Babylon - Lights exported as Meshes?

### ISSUE THREAD

**Issue by echadwick-wayfair** [BabylonJS/Exporters#327]
Max2Babylon 1.2.40
3ds Max 2018.4

Lights are being exported as meshes, not as lights.

![2018-09-21 09_55_08-babylon js - export scene to babylon or gltf format](https://user-images.githubusercontent.com/40177036/45888547-5392c980-bd8c-11e8-80be-85bfc7d20d97.jpg)

![2018-09-21 09_57_49-babylonjs - light_and_sphere glb](https://user-images.githubusercontent.com/40177036/45888561-57bee700-bd8c-11e8-8526-b0d790b1a5f4.jpg)

![2018-09-21 10_00_30-light_and_sphere max - autodesk 3ds max 2018](https://user-images.githubusercontent.com/40177036/45888565-5a214100-bd8c-11e8-8be0-ae6036cb4835.jpg)

[light_and_sphere_Max2018.zip](https://github.com/BabylonJS/Exporters/files/2405824/light_and_sphere_Max2018.zip)

**Comment by deltakosh** [comment]
They are exported as both actually (so you still have a node to see it if you want to debug)

**Comment by deltakosh** [comment]
(Or they should be) adding @kcoley to check

**Comment by kcoley** [comment]
Hi @echadwick-wayfair .  The exporter exports the light as a mesh and a light if exporting to .babylon file.  However, if using .glb or .gltf, lights are currently not supported yet since the official glTF lights extension has not yet been ratified.  Though we plan on implemented it once the extension is ratified.
