### ISSUE TITLE
Upgrade to Blender 2.8

### ISSUE THREAD

**Issue by hassanshaikley** [BabylonJS/Exporters#334]
Getting `AttributeError: RNA_Types object has no attribute 'Lamp'` in the Blender 2.8 Beta that is soon to be released.

: )

I might take a peek at this later if I have a minute.

**Comment by Palmer-JC** [comment]
This minor problem & a few others have already been fixed in the [EEVEE branch](https://github.com/BabylonJS/Exporters/tree/EEVEE) of the repo.

There is no 2.8 Blender beta.  It is an alpha as of yesterday.  Whenever is is declared production, I am sure many people's workflow will dictate that they use 2.79 for some time.

The version of exporter in the EEVEE branch now cannot even be tried, since they changes how menu items get added.  I tried modifying this adding the menu item to the export menu, from an example plug-in, but it just errors.  This is not committed.

A major re-write of how materials are export is required.  The matrix math of bones needs to change.  Getting a temp copy of geometry with modifiers applied also fails, so not only does that need to change, but do not know if there is anything after that.
