### ISSUE TITLE
Animations with movement of the Bip001Pelvis does not translate properly

### ISSUE THREAD

**Issue by VentuzDennisDworak** [BabylonJS/Exporters#359]
i have used a simple biped and very basic mesh, used the mixamo tool to apply a "samba" animation.
This animation is translating the whole body a bit, Imported the animation back into 3dsmax as FBX animation looks good.

Exporting the animation as gltf and binary and using different tools the result is different:
the bip001Pelvis looks like it is "nailed/fixed" therefore no correct body rotations or translations.

As another info: the walking animations, where characters are NOT in place are also not working properly.

please see attached files

the site to apply and download animations is mixamo.com

thanks
[danceanimation.zip](https://github.com/BabylonJS/Exporters/files/2519049/danceanimation.zip)

**Comment by kcoley** [comment]
@VentuzDennisDworak I'll take a look

**Comment by kcoley** [comment]
@VentuzDennisDworak I think I know where to investigate to fix this.  In the meantime, you could use FBX2GLTF to convert your mixamo model which seems to work (https://github.com/facebookincubator/FBX2glTF)

**Comment by VentuzDennisDworak** [comment]
@kcoley 
Great Thanks, 
just wanted to report that ;)

**Comment by kcoley** [comment]
@VentuzDennisDworak sorry for the delay, but this took me longer than I expected to trace down.  

It turns out that the scene you sent me has a Bip001 node excluded from export in the Babylon.js Animation Groups menu.  To get the animation to work as expected, the node would have to be included in the animation group by selecting "Include Node" in the right-click menu.  Here is a reference screenshot:

![image](https://user-images.githubusercontent.com/3946928/51217421-eb3c9a80-18dc-11e9-9217-dd866228ffb6.png)

And here is the generated animation:

[dance.zip](https://github.com/BabylonJS/Exporters/files/2761941/dance.zip)

Hope this clarifies things!
