### ISSUE TITLE
[Max][glTF] Unexpected texture renaming

### ISSUE THREAD

**Issue by EtagiBI** [BabylonJS/Exporters#379]
Hello,

It seems that the exporter renames _some_ (!) original textures to something like "Material #40_baseColor". It's not only confusing but also causes errors in some receiving applications that don't like spaces in names. 

Is it possible to leave textures names untouched?

**Comment by deltakosh** [comment]
Pinging @bghgary

**Comment by bghgary** [comment]
I think you are talking about the glTF loader and not the exporter. I recently made a change to the glTF loader that updates the names of the textures. Can you attach the glTF that you are using?

The reason for this change is that glTF textures are not a 1:1 mapping to Babylon textures, so it is also confusing to use the texture name since it may appear multiple times. But that said, I'm okay with reverting it or coming up with a different solution if it is an issue.

**Comment by EtagiBI** [comment]
Here're both 3DS Max original model and exported GLTF:
[3DSMax_original.zip](https://github.com/BabylonJS/Exporters/files/2593896/3DSMax_original.zip)
[GLTF_Exported.zip](https://github.com/BabylonJS/Exporters/files/2593897/GLTF_Exported.zip)

As you can see, diffuse map was renamed in GLTF.

**Comment by kcoley** [comment]
@EtagiBI I'll take a look

**Comment by kcoley** [comment]
@EtagiBI just merged a fix for this (https://github.com/BabylonJS/Exporters/blob/master/3ds%20Max/Max2Babylon-1.3.12.zip)

Feel free to reopen if the problem comes up again
