### ISSUE TITLE
[Max] Export failed with nested MultiMtl: Index was outside the bounds of the array

### ISSUE THREAD

**Issue by Ben-Mack** [BabylonJS/Exporters#384]
I've occurred this error: Index was outside the bounds of the array
![error](https://user-images.githubusercontent.com/6309393/48685336-5b35e980-ebe8-11e8-87f7-47857eac173d.PNG)

This error only happen when there is a nested `Multi/Sub-object` material with specific config like this:
![material](https://user-images.githubusercontent.com/6309393/48685327-51ac8180-ebe8-11e8-8af6-806856907f3d.png)

The scene will export successfully if the `Child-MultiMtl` has material with the same ID as the slot it connected to on `Parent-MultiMtl`:
![good-config](https://user-images.githubusercontent.com/6309393/48685776-a7822900-ebea-11e8-8aab-76a9ae3073c8.png)

Download this scene here: [MultiMtl-bug.max](http://s000.tinyupload.com/index.php?file_id=40266101646113572530)

**Comment by Selmar** [comment]
We've also had problems where a multimaterial with an empty slot would cause problems, assigning wrong material indices to the resulting gltf.

**Comment by sebavan** [comment]
Our exporter devs are in vacation at the moment, so this will be check in about a week :-)

**Comment by kcoley** [comment]
@Ben-Mack @Selmar sorry for the delay in response.  After doing some testing with this, it looks like mapping a multi-material to another multi-material causes issues with the exporter since this does not map well to babylon.  If you export to babylon file format instead of glTF, you will see that this does not work as expected.  In this case, it would be better to use one multi material.  I will add documentation for this and add a warning to the exporter to warn against this.

**Comment by kcoley** [comment]
Just merged an update for this.  The exporter would now display a warning and not export the sub-multi-material.
