### ISSUE TITLE
[Max][glTF] Texture distortion

### ISSUE THREAD

**Issue by EtagiBI** [BabylonJS/Exporters#402]
Hello,

Some textures completely change their look after export. My export settings are as follows:
![image](https://user-images.githubusercontent.com/20855725/49648032-39d95800-fa46-11e8-894d-89f6374f92ef.png)

Test models:
[Model_to_Test.zip](https://github.com/BabylonJS/Exporters/files/2657216/Model_to_Test.zip)

**Comment by kcoley** [comment]
@EtagiBI it looks like you are using a Standard Material.  For glTF is preferable to use a Physical Material.  Otherwise, it attempts to modify the textures to convert Standard Materials to PBR Materials, which may not look as expected.  Here are some docs on generating glTF files with the Babylon 3ds Max exporter: https://doc.babylonjs.com/resources/3dsmax_to_gltf#pbr-materials
