### ISSUE TITLE
Create a 3ds Max and Maya importer for glTF/glB

### ISSUE THREAD

**Issue by echadwick-wayfair** [BabylonJS/Exporters#428]
We would like a method to unpack and import GLB files into 3ds Max. 

Ideally the textures would be unpacked into separate files, the meshes imported into 3ds Max, and it would create Physical Materials with the textures plugged in.

See also #184.

**Comment by echadwick-wayfair** [comment]
I've figured out a way to do this, but it's cumbersome.

Open Asset Import Library https://github.com/assimp.

assimp export mymodel.glb -ffbx
\\ converts a glb into a fbx model.

assimp extract mymodel.glb
\\ extracts textures from a glb, in their native format (jpg or png).



We would love a native importer!

**Comment by deltakosh** [comment]
Yeah I would like to get a simpler way. We are actively hiring a dev to help us on the exporter/importer :)

**Comment by Drigax** [comment]
same as #184, we _should_ have an importer to pair with our exporters. Unfortunately I don't see myself being able to dedicate a significant amount of time to this for the next few months due to its complexity and scope. 

I hope to eventually get to it, but if anyone thinks that they can do it now, feel free :).

**Comment by sebavan** [comment]
Grouping with #184 as it might be easier to tackle them both at once.

**Comment by sebavan** [comment]
Scope should be:
- [ ] GLTF
- [ ] GLB

in both:
- [ ] Max
- [ ] Maya

**Comment by teaguer** [comment]
Is there already any 3dsmax plugin to import glTF files?

**Comment by echadwick-wayfair** [comment]
> Is there already any 3dsmax plugin to import glTF files?

Not that I could find. I've searched via Google, and also in the two main repositories for Max add-ons: http://scriptspot.com and http://maxplugins.de

The only way I found was to use ASSIMP. Which is fairly laborious. I have to re-create the materials manually after importing the meshes, but the incoming materials at least have empty bitmaps with corresponding names. Could probably be streamlined with a bit of MAXScripting.

**Comment by Bug-Reaper** [comment]
@echadwick-wayfair 
The method you outline is good but unfortunately that converter doesn’t support some things such as blendshape animations. I currently use blender to convert gltf->fbx.

+1 Support for a native gltf importer for maya and 3DS max

**Comment by deltakosh** [comment]
I'm closing this issue as we do not plan to do it and Autodesk will probably soon publish one

**Comment by DoomsdayOrange** [comment]
> I'm closing this issue as we do not plan to do it and Autodesk will probably soon publish one

Autodesk has yet to do that rip

**Comment by MarkusAmbrus** [comment]
Still nothing?

**Comment by Inori** [comment]
Autodesk published their gltf exporter, no importer yet.

**Comment by echadwick-artist** [comment]
I've been using this one lately. Not free, but it does have both import and export, it supports almost everything in glTF, and the developer is very responsive to requests. A win in my book!
https://nu1963u.wixsite.com/custom3dsmax/gltfpluginfor3dsmax

**Comment by echadwick-dgg3d** [comment]
I continue to use the plugins I mentioned before. I've been in contact with the developer to ask for various features, and they always respond promptly, and integrate the requested features. They even have deep support for extensions that haven't been ratified yet, like Physics and Interactivity. 

Anyhow, I highly recommend this plugin, rather than trying to write your own. It's affordable, and it's a decent amount of work to write your own importer/exporter. 

![Image](https://github.com/user-attachments/assets/c92e3606-fe96-40ac-a38d-e54f31ed0164)

**Comment by echadwick-dgg3d** [comment]
$80 USD per year. More info on that page: https://nu1963u.wixsite.com/custom3dsmax/gltfpluginfor3dsmax#:~:text=Price%2C%20License,the%20license%20period.
