### ISSUE TITLE
blender 2.7.9

### ISSUE THREAD

**Issue by weshuiz** [BabylonJS/Exporters#457]
you asume that you hvae the latest of blender
indeed 2.80 is indeed the newest version of blender
but blender 2.8.0 is open beta and not a stable release yet
my request is for blender 2.7.9 exporter i do not want to update to a unstable version
just to get the model converted please make/get a 1.7.9 version (back)

**Comment by Palmer-JC** [comment]
The last version for Blender 2.79, exporter version 5.6, is also available in the same [directory](https://github.com/BabylonJS/Exporters/tree/master/Blender).

Since a zip file does not make any changes to the files, you may un-zip them & edit if you wish.  The repo no longer breaks them out.  This zip file will be moved to the deprecated directory once 2.80 put into production.

Also, 2.80 has been in development for years.  While I am frustrated that I cannot find things with everything moved around, it is very stable at this point.
