### ISSUE TITLE
Simultaneous rotation and tiling support

### ISSUE THREAD

**Issue by EtagiBI** [BabylonJS/Exporters#467]
Hello,

Is it possible to add simultaneous rotation and tiling support? 
For example, I have a texture with following settings:
![image](https://user-images.githubusercontent.com/20855725/54593199-d18c1080-4a4f-11e9-812c-624e728e249a.png)
When I try to export a model with this texture, I get a warning from exporter:
![image](https://user-images.githubusercontent.com/20855725/54593261-fb453780-4a4f-11e9-885f-9066f311f76a.png)

**Comment by EtagiBI** [comment]
I would also like to clarify one thing. Is it **necessary** to use KHR_testure_transform extension for export if any of my textures has tiling and/or rotation?

**Comment by deltakosh** [comment]
Yes unfortunately as the uv transform were not initially in gltf spec

**Comment by Drigax** [comment]
Hi @EtagiBI

Looking at our current implementation, we do support simultaneous rotation and tiling, with one major caveat: **We cannot support using a non-uniform UV tiling with rotation**

There's a few fun threads of discussion regarding the current limitations of the KHR_texture_transform extension [here](https://github.com/KhronosGroup/glTF/issues/1563#issuecomment-490259585) and [here](https://github.com/KhronosGroup/glTF-Sample-Models/issues/177#issuecomment-499243880), but the gist of this is that due to how [the spec calculates the texture transform matrix](https://github.com/KhronosGroup/glTF/tree/master/extensions/2.0/Khronos/KHR_texture_transform#overview):
```glsl
mat3 translation = mat3(1,0,0, 0,1,0, Offset.x, Offset.y, 1);
mat3 rotation = mat3(
    cos(Rotation), sin(Rotation), 0,
   -sin(Rotation), cos(Rotation), 0,
                0,             0, 1
);
mat3 scale = mat3(Scale.x,0,0, 0,Scale.y,0, 0,0,1);

mat3 matrix = translation * rotation * scale;
```
Using different U and V scaling values causes the textures to shear as it is rotated, since the transform is multiplied by the rotation before the scale. This leads to inconsistencies between your 3dsMax authored scene and how it is rendered in a glTF compliant engine like Babylon.

However I did discover a bug in how we compute our texture transform when exporting from 3dsMax in investigating this, so we should have better consistency here as well.

I'll also update the warning text to be more accurate and only pop up if we use a non-uniform texture scale.
