### ISSUE TITLE
Max2Babylon: Alpha Source bug, Base Color JPG and Bump PNG?

### ISSUE THREAD

**Issue by echadwick-wayfair** [BabylonJS/Exporters#470]
Physical Material with a Bump PNG and a Base Color JPG causes the exported glTF material to use alphaMode Blend.

According to this thread, only a PNG in the Base Color input should cause this behavior.
https://github.com/BabylonJS/Exporters/issues/300#issuecomment-419417401

Is this a bug? Or intended behavior? It seems to me only a Base Color PNG should trigger this. 

I would prefer PNG not to enable Blend by default, even if it's caused by an Autodesk bug. Also it seems to me that depth-read and depth-write should be options, not assumptions of alphaMode Blend. But that's probably getting too far off-topic!

Thanks for your help on this.

![image](https://user-images.githubusercontent.com/40177036/54721468-7aae3600-4b38-11e9-85e9-13c3fad8771e.png)

[gltf_png_bump_blend.zip](https://github.com/BabylonJS/Exporters/files/2990255/gltf_png_bump_blend.zip)

Windows 10 Enterprise
3ds Max 2018.4
Max2Babylon 1.3.33

**Comment by deltakosh** [comment]
Pinging @PatrickRyanMS

**Comment by PatrickRyanMS** [comment]
@echadwick-wayfair, I tried to repro your issue and was unable to do it. The only difference for my setup is that I have 2019 installed and when exporting your Max file without changing any settings with 1.3.33, this is my result: 

![BlendModeTest](https://user-images.githubusercontent.com/31326855/54724326-e045f680-4b27-11e9-883d-b741c6ed76fc.PNG)

I am in the process of getting an installer for 2018 right now, but I don't know if it will be SP4. Hopefully that will be the case and I'll try running it again.

One of the things I want to tackle once with our future exporter releases is a more explicit setting for blend mode in the UI rather than having our users be limited to file format or needing to manually edit the glTF file. I'll let you know if I can repro your issue.

**Comment by PatrickRyanMS** [comment]
I was able to get a copy of 2018 installed, but I don't have a drop of 2018.4. It also exported correctly in 2018:

![BlendTest2018](https://user-images.githubusercontent.com/31326855/54733365-84df2d00-4b56-11e9-8e96-711add2b3940.PNG)

Let me reach out to our exporter guys to see if there may be a bug in 2018.4. In the mean time, to get you unblocked, you can edit the glTF easily in something like VS code. You are looking for the "alphaMode" parameter of your material which needs to be OPAQUE:

![VScode](https://user-images.githubusercontent.com/31326855/54733531-57df4a00-4b57-11e9-8d49-068a54fbea0e.png)

**Comment by echadwick-wayfair** [comment]
Hmm, you're right, that file isn't causing it any more. Not sure what changed. Maybe we opened the Bitmap node, which then set the Alpha Source flag?

Here's a reset of that setup, which still causes the bug for me. This is using "Export & Run".

![image](https://user-images.githubusercontent.com/40177036/54755253-f1d8de00-4bbb-11e9-94a0-2f9f5c2a5f06.png)

[gltf_png_bump_blend_v2.zip](https://github.com/BabylonJS/Exporters/files/2992215/gltf_png_bump_blend_v2.zip)

**Comment by PatrickRyanMS** [comment]
I figured out what is going on here. In looking at your new model, I had been concentrating my search around the base color map, but the problem here is in the normal map. The normal map on your asset is a PNG, which does have image alpha. In the bitmap texture settings, your normal map is pointing to the Image Alpha for the Alpha Source rather than None (Opaque) like you have set up for your base color map. Changing the normal map to None for Alpha Source fixes the issue. 

![ImageAlpha](https://user-images.githubusercontent.com/31326855/55035390-16c2bc00-4fd5-11e9-9e77-57e9573b424b.png)

**Comment by echadwick-wayfair** [comment]
Bump shouldn't affect transparency though. 

This should only be triggered if there's a PNG in Base Color, in which case the intention is for the alpha channel to be transparency.

Alternatively if there's a bitmap in the Transparency input, in which case either the intention is for the alpha channel to be used as transparency, or else the rgb, depending on which Alpha Source radio button is used.

**Comment by PatrickRyanMS** [comment]
I agree with you that the only channel that should affect the blend mode in a material is on the base color input. We are looking into why this is the case right now to solve it, This work around is just to help unblock you while we get get this issue resolved.

**Comment by echadwick-wayfair** [comment]
Thanks Patrick! 

Not a blocker on our end; we're making sure to tag the Alpha Source before export. Just want to report bugs as soon as we see them.

**Comment by PatrickRyanMS** [comment]
Thank you for reporting them! Really appreciate knowing what hurdles you face so we can get rid of them.

**Comment by echadwick-wayfair** [comment]
Interesting. I set the normal map Bitmap node's Alpha Source to None (for the PNG), but the Blend mode was still being applied on export. The exporter only set it to Opaque after I opened the Base Color's bitmap node (with the JPG). Not sure if that's relevant.

I noticed this while creating the test for my recent request about adding support for the Normal Bump node.

**Comment by Drigax** [comment]
@echadwick-wayfair, your last experiment was pretty insightful, I'm pretty convinced that this is a bug in 3ds Max.

Sorry for the delay, I set a breakpoint to where we retrieve the base color texture from Max, but the jpg is configured in Max as having an Alpha Source of 0 (Image Alpha in the Max GUI):
![image](https://user-images.githubusercontent.com/3952729/56778772-e5344080-678c-11e9-8c42-cd60609167fb.png)

Which causes us to construct the exported base color BabylonTexture as having alpha, and the Material to use AlphaMode Blend:
https://github.com/BabylonJS/Exporters/blob/24aaddd279cbd690c7ebebba1a627ced6cf6a8f4/3ds%20Max/Max2Babylon/Exporter/BabylonExporter.Texture.cs#L250
https://github.com/BabylonJS/Exporters/blob/24aaddd279cbd690c7ebebba1a627ced6cf6a8f4/3ds%20Max/Max2Babylon/Exporter/BabylonExporter.Material.cs#L407

The proper AlphaSource value isn't set until you inspect the texture in the material editor:
![image](https://user-images.githubusercontent.com/3952729/56779410-c2575b80-678f-11e9-8cb7-ab5eab39577e.png)

After which the material is exported properly 🤦

I'll look into filing a bug report with Autodesk using the provided POC.
