### ISSUE TITLE
Max2Babylon: Normal map should use Normal Bump node

### ISSUE THREAD

**Issue by echadwick-wayfair** [BabylonJS/Exporters#472]
It would help if the Exporter supported a normal map loaded in a Bitmap node, connected into the Normal input of a Normal Bump node, then connected into the Bump Map input of a Physical Material. 

This is how 3ds Max always expects normal maps to be setup for rendering internally, either using its viewport shaders or using Arnold or even for other renderers like V-Ray.

However, the Max2Babylon exporter currently requires a normal map to be loaded in a Bitmap node, connected directly into the Bump Map input of a Physical Material.

Can this kind of support be added? Thank you!

Windows 10 Enterprise
3ds Max 2018.4
Max2Babylon 1.3.33

![image](https://user-images.githubusercontent.com/40177036/55113861-cae84380-50b6-11e9-9c37-b7d17f039004.png)

**Comment by Drigax** [comment]
Ok, I agree that we should fix this. I probably won't be able to get to this for ~2 months due to some higher priority things to address. If anyone wants to take this on in the meantime, feel free.

**Comment by sebavan** [comment]
@echadwick-wayfair I totally agree even more cause setting up a bump directly results as using the texture intensity in the viewport vs a standard use of normal maps.

I will add the bump supports from the normal node in.

At first only the normal part of the node will be supported because to support both we would need to rerender a baked output of the node (I will check later on what we could do for this).

I hope to have by end of day.

**Comment by sebavan** [comment]
Good news is our new Continuous Delivery looks promising, @echadwick-wayfair , you can find associated release files here if you want to test (in the assets at the bottom) : 
https://github.com/BabylonJS/Exporters/releases/tag/preRelease20190611.9

**Comment by cptSwing** [comment]
This has not made it into the master branch yet, am I correct? Thanks for an answer ;-)
