### ISSUE TITLE
Max2Babylon, Physical Material, how disable backface culling?

### ISSUE THREAD

**Issue by echadwick-wayfair** [BabylonJS/Exporters#475]
If we're using Max2Babylon with the Physical Material, is there a way to disable backface culling, to enable 2-sided rendering as a material setting?

Also can we set this option via MAXScript?

I can't find any mention of culling in the docs, other than a post about the 2-sided checkbox in a Standard material. But Standard doesn't support PBR.

Do we need to add a Custom Attribute to disable backface culling?
https://github.com/BabylonJS/Exporters/blob/master/3ds%20Max/MaxScripts/BabylonMaterialAttributes.ms

Thanks!

**Comment by PatrickRyanMS** [comment]
@echadwick-wayfair, I have wanted to add extra options to the exporters for a while and backface culling is definitely one of them. My question for you would be we have two Babylon dialog windows, one under the right click of an object, and the export window itself. Since this would be a per material option, would it make more sense to you for those options to be under the right click context menu or would you prefer to see a list of materials in the export UI where you can set all the needed parameters such as backface culling at once? Part of me says that it would be better not to create more steps at export, but the other part of me doesn't like separating material properties into a context menu since we can't control these options in the slate editor.

**Comment by echadwick-wayfair** [comment]
Hi Patrick! I like the current Custom Attributes method for Unlit, etc. I think having backface cull there makes the most sense. 

In general I prefer when exporters try to maximize parity with the native renderer. So in this case it would be nice for the exporter to use an existing material option that Arnold also supports. However it seems Arnold always renders back faces, at least I can't find a way to disable it. So a custom attribute seems to be the best method.

About the menus, It's a bit of a mess having a per-object options menu, a per-scene options menu, and also options in the exporter window itself. Why not put all the scene options in the exporter window, or vice versa? Yes the exporter window could get large, but Max has convenient UI controls for organizing options into rollouts, etc.

**Comment by Drigax** [comment]
Hi @echadwick-wayfair, I believe @jdwilder-google helped add support for double sided rendering via his contribution: https://github.com/BabylonJS/Exporters/pull/514. We can now use the Double sided material node.

Would that be a sufficient fix? I'll try to make this available for the next package build of the Max2Babylon exporter.
