### ISSUE TITLE
Export custom Attributes from Maya

### ISSUE THREAD

**Issue by Mudoglu** [BabylonJS/Exporters#476]
Is there any way to export custom Attributes from Maya with the Babylon Exporter?

In maya you can asssign Attributes to objects.
We would like to assign a lightmap Attribute to connect later the lightmap texture to the right shader.

https://forum.babylonjs.com/t/export-custom-attributes-from-maya/2518/2

If needed i could provide a scene showing what we like todo.

Cheers

**Comment by deltakosh** [comment]
Thanks a lot, we're gonna add that to the todo :)

**Comment by deltakosh** [comment]
Pinging @PatrickRyanMS FYI I think we should consider it for our UI rework)

**Comment by kadirilkimen** [comment]
I think 3ds max exporter plugin may have similiar function.
In 3ds max, we can append custom attributes to any object ( floats, strings etc ).
It would be very good if babylon exporter append this custom attributes to object's data.

I dont know if it is same task ( because i dont know anything about Maya) , but i think it worth to mention here :)

**Comment by sebavan** [comment]
Closing for house keeping as we are grouping all the UI work in one place #537
