### ISSUE TITLE
[3DS Max] Pivot exports as dummy object

### ISSUE THREAD

**Issue by EtagiBI** [BabylonJS/Exporters#505]
Hello,

I've noticed that sometimes model's pivot point exports as a dummy object (helper). Usually it happens when a pivot point isn't a center of a model (see below).
![image](https://user-images.githubusercontent.com/20855725/57353545-43e0bd80-7182-11e9-9281-532eafb4997e.png)

It seems that exporter doesnt' recognize a pivot point and converts it into a dummy object (helper). Needless to say that it's a wrong behavior.

Model sample:
[Table_Pivot.zip](https://github.com/BabylonJS/Exporters/files/3155780/Table_Pivot.zip)

**Comment by Drigax** [comment]
Sorry for the slow response, I've been a bit busy resolving some of our exporter issues :)

I'll try to take a good look at this in the next 2 weeks to resolve this, but do we want to export these objects such that their new origin is the pivot?

**Comment by Drigax** [comment]
Looking at the behavior in max, I'm unsure what the issue you're reporting is. I may not be well versed enough in the terminology, so please feel free to reopen this issue with clarification.

In your scene file, you have a number of meshes grouped under AM_138_034 with a transform at the world origin:
![image](https://user-images.githubusercontent.com/3952729/58995617-c1134880-87a9-11e9-89fa-a9fa8567d94f.png)

The resulting hierarchy in our exported scene is:
![image](https://user-images.githubusercontent.com/3952729/58995769-66c6b780-87aa-11e9-9365-7988ce39a2b2.png)

Where the group parent is oriented at the origin, parented to a __root__ transform in order to convert the Right Handed coordinate system of 3dsMax to the LeftHanded coordinate system of Babylon.

Moving the pivot point via the AdjustPivot dropdown in Max results in an exported scene of:
![image](https://user-images.githubusercontent.com/3952729/58996720-4dc00580-87ae-11e9-9f91-7240e4914117.png)

Where the exported node is the object's pivot...hmm...

This seems like expected behavior going off of the 3dsMax documentation:
https://knowledge.autodesk.com/support/3ds-max/learn-explore/caas/CloudHelp/cloudhelp/2017/ENU/3DSMax/files/GUID-A4853FF5-8657-4ED0-92E0-98F4CFB445A3-htm.html
