### ISSUE TITLE
Maya Exporter to support alphaMode MASK and alphaCutoff

### ISSUE THREAD

**Issue by vanlicht** [BabylonJS/Exporters#535]
Hi,

Really enjoy the Maya Exporter  but find the feature still missing to support alphaMode MASK and alphaCutoff values. Any solution already exists that I miss? Thanks!

**Comment by Drigax** [comment]
I'm not entirely sure off hand. @vanlicht, can you provide a sample .maya scene to look at to test correctness of the implementation? I think we have a few other alpha channel related issues going off of #473, sounds like they're related.

**Comment by vanlicht** [comment]
Hi @Drigax,

Please see the attached. Thanks.

[gittree.zip](https://github.com/BabylonJS/Exporters/files/3259203/gittree.zip)

**Comment by Drigax** [comment]
Hi @vanlicht, I'm not sure if the difference in your results are due to AlphaMode export settings. Some leaves aren't rendered in your left example due to backface culling of the leaf meshes. Changing the material properties in the Babylon engine, I can see:

![image](https://user-images.githubusercontent.com/3952729/59125647-cdb5af00-8917-11e9-9d9c-24765a0e13d8.png)
Where the left tree's leaves uses a material with backface culling enabled, while the right tree's leaves' material has backface culling diabled.

Which appears to replicate your initial test.

I'll try to create a test rig for testing the AlphaModeMask & AlphaCutoff capabilities, more similar to the the one used in the GLTF spec:
https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/AlphaBlendModeTest

**Comment by vanlicht** [comment]
Hi,
Yes I am aware if the doubleSided issue, which at the moment there is no support from Maya exporter I think. For the desired result I had to manually add it in the glTF code. 
Though, there is difference of the tree in BLEND mode versus MASK mode, wonder if you noticed the difference. Thanks.

**Comment by Drigax** [comment]
Thanks for the clarification. I don't have an eye for that fine of detail, so I wanted to address the most obvious issue first. 😊 

But i can see the need to support removing the leaves' white halo via a hard alpha test. 

Currently, Maya doesn't expose texture Alpha blending modes, nor per-material back face culling in the Maya exporter, and our exporter implementation doesn't currently extend that functionality (most likely due to implementation complexity).

Some goals of our exporter UI revamp would be to expose these options, and ideally using as much Maya & 3dsMax native UI as possible, and I think that it would be best to support this as part of a drastic change rather than hacking in a stopgap to support this right now.
