### ISSUE TITLE
Revamp the exporter UIs and add the missing requested export flags support

### ISSUE THREAD

**Issue by sebavan** [BabylonJS/Exporters#537]
For both Max/Maya, redesign the exporter UIs.

This should help addressing :

- [x] Initial design exploration for feasibility
- [x] GLTF exporter should be shared across max and maya.
- [x] BackFace Culling #529 
- [x] Double Sided #529
- [x] Transparency Mode #535
- [x] Max Simultaneous Lights #501 
- [x] Custom Attributes #476 
- [x] Animation Only #525 
- [x] Add support for 3dsmax 2020 #618

All the above issues have been grouped here to simplify the development of the new UI.

Do not hesitate to add to the list.

**Comment by Drigax** [comment]
#566 has been checked in, decoupling the Babylon->GLTF exporter from the 3dsMax Babylon exporter implementation.

All that's left to do for 2) is to refactor Maya's exporter to use the shared implementation.

**Comment by Drigax** [comment]
With #593 checked in we can finally check off 2)!

**Comment by noalak** [comment]
I'm currently implementing a solution for the user to specify the extra material attributes in Maya (backface culling, transparency mode, max simultaneous lights and unlit).
Stay tunned for any progress!

**Comment by jamespedid** [comment]
Is custom attributes a low hanging fruit that might be able to be taken out quickly? This would provide tremendous value to me. I'd like to contribute if possible, but I don't have either 3D modeling tool.

**Comment by deltakosh** [comment]
Hey @jamespedid ! @noalak is making a lot of progress and should be able to do a PR really soon.
Form custom attributes, help would definitely appreciated but we cannot help on the 3D modeling license unfortunately

**Comment by noalak** [comment]
We are working on the export animation only feature (#525).
This issue is related to #632.

The 3dsMax exporter is updated to have 2 extra parameters: ExportAnimations and ExportAnimationsOnly. Those parameters drive the export process in order to export only the geometry and then in another export animation(s).

Find attached an example of the resulting babylon and glTF files [elf.zip](https://github.com/BabylonJS/Exporters/files/3878992/elf.zip).

Notice that the glTF animation files use an extension named "AnimationsOnly".
This is the only one reference to an extension, as opposed to what is discussed by @Selmar here https://github.com/KhronosGroup/glTF/issues/1448.
The reuse of an animation (sampler) is supposed to be driven by the channels array according to glTF specs. So we don't see the interest of having an extension specified in each animated node. Maybe I am missing something though.
Anyway, it's a good starting point for the export process.


Now for the import process, our goal is to support the 2 following use cases:
1)  user = anyone: Drag&drop geometry file into the sandbox. Then drag&drop an animation file.
2) user = developer: Load a geometry file using SceneLoader.Load method. Load an animation file using a new method SceneLoader.ImportAnimation.

**Do you confirm the use cases ?**

For that, we are planning to load the animation file as a new scene and then clone and retarget the animations to the geometry scene.
The animation scene can after be deleted or kept.
The new animations would either replace or append to previously imported animations. The sandbox would have a default behavior (replace).
The append method could either be smart in order to avoid duplication or not.

This method has the advantage of being format independant (babylon or gltf).

We just need a way to detect that the file being loaded is an animation file.
For glTF we can add an extension that would flag the scene as an animation scene.
For babylon, @deltakosh told us that the animation loading is already done. Do you have a clue on what it is ?

**Comment by Selmar** [comment]
How do you retarget the animations? The glTF specification does not guarantee anything about uniqueness in node names. It is for this reason the target id is necessary.

Also, the `animation_run.gltf` you've given has this defaults and invalid data like this in the gltf, is it an older export?
```
      "rotation": null,
      "scale": null,
```

**Comment by Selmar** [comment]
Using a target id also allows the user to completely omit the node hierarchy in the animation-only file.

That being said, we already have an implementation for the gltf animation-only export, as described in the post you referenced, perhaps it is worth pushing this upstream? @elpie89

**Comment by elpie89** [comment]
I will push it before the end of the day

**Comment by Drigax** [comment]
Completing Backface Culling, Unlit, Double Sided, Max Simulteous Lights and Transparency Mode via #668

**Comment by jamespedid** [comment]
I've noticed that the custom attributes do not export if they are defined on a set in Maya. Is it possible to extend support of custom attributes to these objects as well?
