### ISSUE TITLE
Add support for Cinema4D (.gltf / .babylonjs)

### ISSUE THREAD

**Issue by deltakosh** [BabylonJS/Exporters#56]

**Comment by ThibaultJanBeyer** [comment]
+1

**Comment by MacroMachines** [comment]
crazy?!  would this be a C4D plugin or ?

**Comment by deltakosh** [comment]
Probably :)

**Comment by DonutKilla** [comment]
+3

**Comment by jameslashmar** [comment]
+1

**Comment by couch4** [comment]
+4D

**Comment by readyforchaos** [comment]
+1

**Comment by donmccurdy** [comment]
Maxon just released a glTF exporter for Cinema4D to Maxon Labs: https://labs.maxon.net/?p=3360

**Comment by deltakosh** [comment]
Woot!
Closing the issue then :D

**Comment by kentbarber** [comment]
I don't mean to re-open this. But since I am a C4D developer who is currently using Babylon I was wondering if it would still be useful to have a babylon.js exporter natively in C4D as a plugin. Is this something the community would want?

I may also write my own glTF exporter as well and integrate the new Basis texture compression into the pipeline, as well as sample textures and simplify the texture export process (maybe include baking) and a better PBR workflow.

If this is something that interested people then let me know.

**Comment by DonutKilla** [comment]
Yes, I would use a c4d Babylon exporter with compression and rounding vertices. I use glTF but a Babylon.js exporter I would use more often.

**Comment by flopanzer** [comment]
> Also thinking of adding in custom tags, objects, UI workflows and custom dialogs for C4D to essentially setup a full interactive scene ready for export and immediate play with no additional steps.
> 
> If this is something that interested people then let me know.

Yes, please! Let me know if you need help with testing!

**Comment by DonutKilla** [comment]
Yes, Do it!

**Comment by jameslashmar** [comment]
Have you guys seen this?
https://labs.maxon.net/?p=3360

**Comment by deltakosh** [comment]
Yeah this is great!!
