### ISSUE TITLE
After last refractoring custom material are no longer supported

### ISSUE THREAD

**Issue by elpie89** [BabylonJS/Exporters#568]
It is no longer possible to have a custom material exporter
The problem came from the file BabylonExpoorter.GLTfMaterialExporter.cs
@Drigax  can you check this?
there was something like this:

`if (materialExporters.TryGetValue(new ClassIDWrapper(maxMtl.ClassID), out IMaterialExporter materialExporter)
                && materialExporter is IGLTFMaterialExporter)
            {
                gltfMaterial = ((IGLTFMaterialExporter)materialExporter).ExportGLTFMaterial(this, gltf, gameMtl,
                    (string sourcePath, string textureName) => { return TryWriteImage(gltf, sourcePath, textureName); },
                    (string message, Color color) => { RaiseMessage(message, color, 2); },
                    (string message) => { RaiseWarning(message, 2); },
                    (string message) => { RaiseError(message, 2); });

that is now refactored but broke the feature

**Comment by Drigax** [comment]
Ah, I see what's happening here. This needed some major reconsideration to work as a shared component. Since the shared GLTF exporter can't know about the Max API when it invokes the custom GLTF exporter, its passed as an `IGLTFMateriaExporter`. and `IGLTFMaterialExporter` was changed to be a modeling API agnostic interface.

The previous `IGLTFMaterialExporter` was renamed as `IMaxGLTFMaterialExporter`, `IMaterialExporter` was renamed to `IMaxMaterialExporter` and that codeblock was never reimplemented. oops.

I'll move this to the MaxGLTFMaterialExporter constructor, and add it to the export parameters on export.

**Comment by Drigax** [comment]
Is there any reason why the custom material exporters are for GLTF export only?

**Comment by elpie89** [comment]
> Is there any reason why the custom material exporters are for GLTF export only?

No we can give this possibility to other formats as well
