### ISSUE TITLE
Animation Group exported do not work for istances of custom material

### ISSUE THREAD

**Issue by elpie89** [BabylonJS/Exporters#574]
Problem after the last refactoring:

Animation group are linked to a meshesList
that in case we are exporting a custom material does not contain the instances.

Actually this idea the animation groups are linked to a mesh I think is wrong.

To test this just write a custom material assign it to a master mesh and an instance. create animation groups of them and export
Only the animation group of the master mesh is exported

**Comment by Selmar** [comment]
I agree with @elpie89 here, he's talking about this piece of code;
```C#
    BabylonNode node = babylonScene.MeshesList.FirstOrDefault(m => m.id == nodeId);
    if (node == null)
        node = babylonScene.CamerasList.FirstOrDefault(c => c.id == nodeId);
    if (node == null)
        node = babylonScene.LightsList.FirstOrDefault(l => l.id == nodeId);
    if(node != null)
    {
        // ... export animation stuff
    }
```

It is/was functional, but it's conceptually "wrong", in my opinion. This is just one example of why, where instances aren't regular meshes so they're not added to the mesh list, which makes sense on its own, but then breaks other systems.

I suppose it's here due to the babylon format not supporting nodes without anything on them? Perhaps it would be good to tackle this in a more explicit way rather than adding dummy meshes to the mesh list.

**Comment by Selmar** [comment]
The second problem here is that instance meshes, for some reason, are added as a "master" mesh if it detects an unsupported or custom material, but as an "instance" mesh in normal situations.

**Comment by Drigax** [comment]
Interesting. Currently a mesh instance that does not share material is considered a unique mesh [due to descrepancy between babylon.JS and 3dsMax implementation of mesh instances](https://github.com/BabylonJS/Exporters/issues/541)

But if a mesh and its instance have the same custom material, and are exported as separate meshes, I'd consider that a bug.

Either way it sounds like we have an animation group that applies to a mesh, and another that applies to an instance, but only the original mesh's animations are exported properly?

I currently have no way to test a custom material exporter, would you be able to help clarify the issue?

**Comment by Selmar** [comment]
The same problem also happens when the material is not recognized (in which case they are the same as well), so you can repro with that.

It's also not hard to create a custom material exporter; just take any of the exported materials' class ids, implement the interface on a new class and move/copy the code. Although for this case moving any code isn't even necessary;

```C#
    public class PhysicalMaterialExporter : IMaxGLTFMaterialExporter
    {
        ClassIDWrapper IMaxMaterialExporter.MaterialClassID => ClassIDWrapper.Physical_Material;

        GLTFMaterial IMaxGLTFMaterialExporter.ExportGLTFMaterial(ExportParameters exportParameters, GLTF gltf, IIGameMaterial maxGameMaterial, 
            Func<string, string, string> tryWriteImageFunc, 
            Action<string, Color> raiseMessageAction, 
            Action<string> raiseWarningAction, 
            Action<string> raiseErrorAction)
        {
            // code, or not...
        }
    }
```

Also, nitpicking, but I've seen we created a wrapper for the custom material exporters, but it's not actually used everywhere (i.e. `BabylonExporter.Material.cs`). I also propose to use a more generic name, because it wraps both babylon and gtlf material exporters, and some helper functions to check if a material is supported.

**Comment by Drigax** [comment]
Thanks for the snippet. I'll have to dig deeper into this in a few days, I'm currently a bit occcupied resolving other fires I've started through the refactor. Luckily it looks like things are 95% working ;)

**Comment by Drigax** [comment]
I see, it looks like there's some issue with our instance checking logic, I modified this to export instance meshes with materials that aren't exported to be exported as instances.

I agree with you @Selmar  on the fix, the easiest way in my opinion to fix this would be to also search our meshes list instances to find the given node during animation export. I'll open a PR with my proposed fixes.

**Comment by Selmar** [comment]
@Drigax This wasn't clear from my post, I see now. Actually, I meant that we shouldn't be checking specific lists, but rather a generic node list. I see no reason at all to only export things that we put in a lights/camera/mesh list.

**Comment by Drigax** [comment]
Well, I'm not sure if, other than skeleton joints, there are anything else that we should consider a node other than meshes, lights, and cameras. I'm satisfied making a change to keep a master "node list" containing the four types of objects that we append to during the export process, but I'm not sure if there's much improvement to be had by doing so.

**Comment by Selmar** [comment]
The proposal fixes the problem at hand. 

What I propose simply aims to get more robust code that doesn't change when adding new, seemingly unrelated, features. We've had a lot of breaking changes recently due to oversights like this.

A node list works, an iterator that iterates over the different types is another option (I understand why it is like this, with dummy meshes to fill the gaps, although it is a bit weird). Perhaps the best option is a dictionary, to speed up the process a bit for large scenes?

**Comment by Drigax** [comment]
Good point, I agree that we should be trying to improve wherever we can to prevent regressing the same code paths. I updated the PR to incorporate a babylon node map where we index by node id, and populate as we traverse our scene tree. This should significantly improve our animation group export time in scenes with alot of nodes.
