### ISSUE TITLE
Animations randomly played

### ISSUE THREAD

**Issue by elpie89** [BabylonJS/Exporters#600]
after last modification, there is some issue in GLTFExporter.Animation.cs on this:
https://github.com/BabylonJS/Exporters/commit/07941f65f986ebf2cb044993ab8bf11112585bfe
just reverting the class everything is ok

A GLTF with many animationsGroup play random animations
Running one of them from visual studio code, for example, all animations are triggered.
I do not understand what was the goal of the refactoring,
I think animationsGroup are calculated in the wrong way

**Comment by Drigax** [comment]
Refactoring without a proper test pass is always a risky endeavor, there's no way around that. Things will break when things are changed since the exporters are pretty complex and in use have plenty of edge cases. 

As we add more functionality, we need more tests to cover them. In the future, it would be nice to include repro scenes so we can do our best to not break you twice (and eventually provide some automation fixture).

The goals of the refactoring [(best explained here)](https://medium.com/@babylonjs/a-tale-of-two-exporters-27d81693a8e2) is to make it easier to bring the Maya and 3dsMax exporters to parity since both had separate Babylon->Gltf implementations. 

I appreciate your help in fixing this regression though, I don't think this will be too easy of an endeavor, and I appreciate any and all support.
