### ISSUE TITLE
Have possibility to export texture in jpg/png formats from 3d max

### ISSUE THREAD

**Issue by Hersir88** [BabylonJS/Exporters#62]
What about adding some way to force image format for textures ?
http://www.html5gamedevs.com/topic/35026-image-format-in-3d-max/

**Comment by noalak** [comment]
Hi Hersir88,

Are you exporting to babylon or gtlf format ?

You want to choose between jpg or png
- only relatively to alpha presence ?
- because you have images in other format (like tga, bmp) and you want to convert them ?

Is it only related to base color and transparency maps ?

If it's only about alpha, what we can do is:
- automatically detect if a texture has transparency and export to jpg / png accordingly
- add a dropdown in export window to "force jpg", "force png", "automatic" (above)

Second option doesn't seem necessary to me as long as first one works properly :)

**Comment by Hersir88** [comment]
Hi, I am exporting babylon file.
And somehow diffuse maps are always exported as pngs for me even if no transparency is in the image. (Physics PBR material for example). Would be nice to somehow force to have it in jpg.

**Comment by Hersir88** [comment]
With auto force to jpg there could be some issues as sometimes you need extra quality that png gives, for text on texture or some thin lines.

**Comment by pierreglibert** [comment]
Hi community :)
I created a post with the same issue here : http://www.html5gamedevs.com/topic/37092-3dsmax-exporter-wrong-compression/.
But I mentionned one more think : we need to control the compression of jpeg.
At this moment, jpeg is too mush compressed and downgrade the quality of the render.
We need an option with the percent of compression of jpeg.
What do you think about that ?

**Comment by noalak** [comment]
Image compression quality set to 100%.

@deltakosh Do we add an option to configure quality % ?

**Comment by deltakosh** [comment]
yes:)

**Comment by deltakosh** [comment]
Closing for now. we will add an option to pick jpg compression
