### ISSUE TITLE
Add support to export "splitted" animation data

### ISSUE THREAD

**Issue by elpie89** [BabylonJS/Exporters#632]
To fully replace an fbx based workflow we should be able to export a GLTF with mesh data and different data files for each animations
If an artist change a keyframe only his animation data file should change

**Comment by elpie89** [comment]
Right now I have no idea on how this should be achieved...I'm open to any ideas/inputs

**Comment by Drigax** [comment]
I'm sure its possible, say we have a scene of a rigged human with a walk cycle, and instead of exporting as a single gltf, we instead export one glTF containing the human mesh/meshes, skeleton and skinning data, and a second glTF containing a skeleton or just a hierarchy of nodes and their animation tracks. 

Ugh, I'm not too sure what's the best way to approach this either, I'm currently looking through the glTF repo to see if this usecase has some best practices outlined.

**Comment by Drigax** [comment]
This sounds a bit like what you're asking for:
https://github.com/KhronosGroup/glTF/issues/1448

In this case, I'd lean towards not including a skin/skeleton in the animation file, but rather include nodes representing the skeleton joints to be animated, and the animation data for each node, so that we don't violate the schema.

The onus would then be on the user to make sure that the data is properly re targeted to their desired mesh in-engine

**Comment by Selmar** [comment]
I have posted our proposed implementation in the link you provided.
