### ISSUE TITLE
3ds Max: Faces of exported meshes are not connected

### ISSUE THREAD

**Issue by ephb** [BabylonJS/Exporters#644]
When exporting a mesh form 3ds Max and then inspecting the resulting gltf or glb file one can see that files tend to be quite large for even the most simple meshes.

This led me to investigate a little further and I checked multiple files which I had exported in Blender.
All faces in the mesh objects are detached / have their own vertices. 

This not only results in much larger files than necessary but also breaks smooth normals depending on the rendering target for example when converting the gltf files to usdz.

Steps to reproduce:

- Create new Max scene
- Create Box
- Export to gltf using Babylon
- Load in Blender
- Move any face and see it is detached

I have attached the duck from the Khronos Group samples in its original glb file and one exported from the BabylonJS exporter. The size difference shows it clearly.

[Duck.zip](https://github.com/BabylonJS/Exporters/files/3694289/Duck.zip)

**Comment by ephb** [comment]
Is there anything I can do to provide more info?

**Comment by Drigax** [comment]
On having detached faces, I believe that that's expected of glTF, since vertices are per-face. for example, I have a cube mesh exported from blender:
![image](https://user-images.githubusercontent.com/3952729/66348206-e4dacc80-e90a-11e9-806d-5f393fac05a8.png)
Where logically, there's 8 vertices that make up the cube, but since the mesh has 12 triangulated faces, the glTF contains 24 vertices.

reimported into Blender, we can see that there is no connectivity between the faces, (except the triangulated quads) as they don't share vertices.

**Comment by Drigax** [comment]
Looking at the imported result of the Maya exporter, I can see a similar pattern, which leads me to think that the lack of connectivity between some edges is expected behavior:
![image](https://user-images.githubusercontent.com/3952729/66355582-a6e6a400-e91c-11e9-82d5-7b11fc7f43e6.png)

But that doesn't explain why there is no connectivity at all in the 3ds_Max exported mesh, so I looked at some of our export logic:
https://github.com/BabylonJS/Exporters/blob/a6161f6704188697f987350a2b1a33846038624e/3ds%20Max/Max2Babylon/Exporter/BabylonExporter.Mesh.cs#L591-596
https://github.com/BabylonJS/Exporters/blob/a6161f6704188697f987350a2b1a33846038624e/3ds%20Max/Max2Babylon/Exporter/BabylonExporter.Mesh.cs#L899-922

Where we would do our pass over the mesh geometry to check if there is already a vertex that shares position & normal before exporting a given vertex if "optimize vertices" is enabled on a given mesh.

After doing so, it appears that the mesh connectivity is preserved for smooth edges, does this work for your duck scene @ephb?

**Comment by ephb** [comment]
Thank you @Drigax for looking into this!
Switching on "Try to optimize vertices" works and the smooth mesh sample of the duck actually comes out smooth, with connected faces and the same file size as in the Khronos sample gallery.
Though I am a bit surprised this is not the default behavior.

**Comment by Drigax** [comment]
I agree, I'll make some changes to flip our optimization logic

**Comment by Drigax** [comment]
After talking with @PatrickRyanMS, I think the best course is to leave this as opt-in, as 3dsMax represents vertices per-face, and its difficult to preserve intended connectivity for this DCC tool, and we don't want to force our users to use this destructive operation by default.

For example, if a mesh contains two verts that share position, normal and UV, they will be optimized as the same vert, even if they are represented as multiple verts and belong to completely different faces in Max. For a given face, we can only really look at every vertex we've seen so far as we process this face, and discard unnecessary vertices if we already processed a vertex that's similar.
