### ISSUE TITLE
Exported model also shows the bones geometry

### ISSUE THREAD

**Issue by sebavan** [BabylonJS/Exporters#651]
*Vicente Penades 12:54 PM*
Hi, I have a question about exporting with BabylonJS in 3dsMAX:  I have a freelance artist working remotely, he is having issues when exporting an animated model: the exported model also shows the bones geometry being exported....  is this a bug? is there a way to solve this?
*Sebastien Vandenberghe 4:23 PM*
This is really weird :disappointed: would you mind creating an issue on the babylonjs exporter repo ? We will have a look shortly. Would be amazing if you could share the model you are using in the issue.
*Vicente Penades 4:25 PM*
I am hesitant to open an issue because I could not validate the model myself... I can upload a MAX file showcasing the issue here... though
*Vicente Penades 4:34 PM*
This file has been forwarded to my by an artist working remotely, he's been trying to export the model to glTF using BabylonJS 20191009.6 . When he tries to export the model, the bones are also exported as geometry.
He is a junior developer, so the model might have something wrong, but he explained to me the process and everything seems fine.

**Comment by sebavan** [comment]
Attachment is here:
[StickTest.zip](https://github.com/BabylonJS/Exporters/files/3713494/StickTest.zip)

**Comment by Drigax** [comment]
(Feel free to relay this to Vicente)
In the StickTest scene, the bones have meshes added to them as guides/handles. You can exclude the meshes from export by right clicking after selecting the mesh, and enabling the "Do not export" option under Babylon...->Babylon Properties.
![image](https://user-images.githubusercontent.com/3952729/66607790-db9b6b00-eb69-11e9-819b-ff1a7c7f7f12.png)

Enabling this will still include and use the node as a skeleton joint if any node in scene is skinned with it.

As as aside, I noticed that the test scene failed to properly export "Cylinder001"'s skeleton:
![image](https://user-images.githubusercontent.com/3952729/66608287-15b93c80-eb6b-11e9-8a27-58ae22cc10bc.png)

In order to prevent this, you must ensure that all the bones that comprise your skeleton are part of the same hierarchy, as Character002 may have been erroneously included in your skinning table (It has no influence on any geometry) :
![image](https://user-images.githubusercontent.com/3952729/66608079-77c57200-eb6a-11e9-9c86-0ad7bb9be309.png)

Let me know if this helps, and feel free to report any issues you encounter in the future 😊
