### ISSUE TITLE
3ds Max - Scale factor not being applied 

### ISSUE THREAD

**Issue by shaileshiyer** [BabylonJS/Exporters#659]
There seems to be a bug when exporting the gltf model with scale factor.The scale factor is not being applied to the model in the gltf export from 3dsmax. Even when changing the scale factor it does not seem to add the scaling root in the exported gltf.

**Comment by Drigax** [comment]
Can you help clarify? What scale factor are you referring to? Also, can you provide a repro scene?

**Comment by Drigax** [comment]
Hi @shaileshiyer, can you help me reproduce this with a Max scene and export result that shows what's going on?

**Comment by Drigax** [comment]
I created a simple scene in 3dsMax with kilometer unit scaling:
![image](https://user-images.githubusercontent.com/3952729/67724610-d11c0680-f99c-11e9-94e9-bd52922898f8.png)

and when exported to glTF, the scaling is applied to the mesh geometry transform, rather than being applied to the root transform. We can see this by inspecting the outputglTF buffer data in the vertex positions of our 1km size cube (though I think we're currently off by a factor of 1000, since glTF units are in meters):
![image](https://user-images.githubusercontent.com/3952729/67724787-6e773a80-f99d-11e9-8663-94674b7ef307.png)

Is this acceptable behavior?

**Comment by Drigax** [comment]
Ah, I'm just silly. I forgot we have a global scene scaling property that's modifiable here:

![image](https://user-images.githubusercontent.com/3952729/67729237-88b91480-f9ad-11e9-8a4e-17f3f5ba15e5.png)

I think this property got a bit lost in refactoring, the logic that creates the root node and whatnot is still in the export code, the value was just never propagated.

I have a quick fix for that. Sorry for addressing this so slowly. 😀

**Comment by Drigax** [comment]
#665

**Comment by Drigax** [comment]
Fix should be available in the 20191028 release 😀

Thanks for reporting this!

**Comment by shaileshiyer** [comment]
Sorry, I just saw the replies now.Hence, could not provide a repro . Thanks for resolving it. Much appreciated. 

> Hi @shaileshiyer, can you help me reproduce this with a Max scene and export result that shows what's going on?
