### ISSUE TITLE
Problem with exporting Babylon CD Release 20191111.2 (3D MAX 2019) in .glb files

### ISSUE THREAD

**Issue by AndresCH10** [BabylonJS/Exporters#682]
Good morning, today working with the babylon plugin, I export all the files with textures made by me (Substance painter) with opacity, but when I use a solid material of max, the opacity goes away.

Could it be a problem of the export options of the material in babylon or would it be of the material itself?

Thank you

----> Model
[Model3D.zip](https://github.com/BabylonJS/Exporters/files/3835947/Model3D.zip)

**Comment by vpenades** [comment]
We're having the same issue on our side.

After inspecting the files, we've found the material AlphaMode property is set to BLEND instead of OPAQUE.

**Comment by Drigax** [comment]
@AndresCH10, what alpha setting are you using for the texture in 3dsMax? If the texture format supports alpha, we drive the alpha blend mode of the material based off the setting.

**Comment by AndresCH10** [comment]
Good afternoon, thanks for answering, my texture is taken in PNG and these are its attributes within the max, I have the same options as in the reference image but it does not export well.
---> 
![Captura de pantalla (148)](https://user-images.githubusercontent.com/56534602/68695177-d7080f00-057a-11ea-8bd8-90efdcb6ca87.png)

On the other hand, the configuration that I have used in the material has been Blinn material.
With the help image, the babylon attributes option I do not have, therefore, I can not check if it works that way, could you tell me how to open that option?

---> imagen
![Captura de pantalla (149)](https://user-images.githubusercontent.com/56534602/68695368-2f3f1100-057b-11ea-8e3b-5c67ad18576a.png)

**Comment by Drigax** [comment]
Hmm, @AndresCH10 , I spent some time setting up a test bench to test the different texture/material export results.

I used 5 types of Materials and base color textures:
1) Base color texture in format that never has alpha channel (jpg)
2) Base color texture in format that supports alpha channel, but texture doesn't have one (png)
3) Base color texture in format that supports alpha channel, texture has channel, and texture setting in Max is set to "Alpha Source - None (Opaque)"
4) Base color texture in format that supports alpha channel, texture has channel, and texture setting in Max is set to "Alpha Source - Image Alpha"
5) Base color texture in format that supports alpha channel, texture has channel with transparent sections, and Texture setting in Max is set to "Alpha Source - Image Alpha"

The results appear to be as one would expect, though the simple geometry here hides the sorting errors that you see with your scene when transparency is applied:
![image](https://user-images.githubusercontent.com/3952729/68728137-47af2b80-057b-11ea-9199-175d16a19aac.png)

The third column appears to be what you're running into, we have a PNG with transparency channel, we set Alpha Source to Opaque, and export, but the resultant glTF shows that we have alphaMode opaque in my testing...
![image](https://user-images.githubusercontent.com/3952729/68728292-c5733700-057b-11ea-867a-da2ec88ea9b1.png)

I'm not sure if I can reproduce what you're running into. Can you send your scene so I can take a closer look?

Here is my source scene, files, and export results:

[Exporters_682_repro.zip](https://github.com/BabylonJS/Exporters/files/3839211/Exporters_682_repro.zip)

**Comment by AndresCH10** [comment]
This is my max 2019 scene.
The scene you sent me, I could not open it due to the max version.


Model3D(Scene).zip](https://github.com/BabylonJS/Exporters/files/3840277/Model3D.Scene.zip)

**Comment by Drigax** [comment]
Sorry, I used Max 2020 to create the testbench. I'll try to recreate it in Max 2019 as well

**Comment by Drigax** [comment]
Looking at the scene, I'm not sure if I'm seeing the issue here.

![image](https://user-images.githubusercontent.com/3952729/68809167-2eac8600-0620-11ea-9e24-07331a1ecdcb.png)

You're using a Standard Blinn material for the mesh, the texture 2019-11-12-PlantaCarnivoraTexture.png is a PNG without an alpha channel, and we have the Alpha Source set to None (Opaque).

I reinstalled the latest exporter v20191113.4 to test on 3dsMax 2019.
![image](https://user-images.githubusercontent.com/3952729/68809325-8d71ff80-0620-11ea-8ebe-701282e5a5f2.png)

I exported the scene using these settings, and the output looks...normal?

![image](https://user-images.githubusercontent.com/3952729/68809390-b1cddc00-0620-11ea-8a2c-09416d5bff2f.png)

@AndresCH10 Can you please confirm that you're using the latest exporter, and have the texture configured with Alpha Source = Opaque?

**Comment by Drigax** [comment]
Ok, revised my test scene to isolate what I think we're trying to do here:

We have 4 permutations, all using the same transparent UV checkerboard with alpha channel gradient:
Physical Material with transparent base color PNG with AlphaSource = Opaque
Standard Material with transparent diffuse color PNG with AlphaSource = Opaque
Physical Material with transparent base color PNG with AlphaSource = ImageAlpha
Standard Material with transparent diffuse color PNG with AlphaSource = ImageAlpha

When exported, both materials with opaque set textures will make the material be exported with Alpha Mode Opaque, and the materials with Image alpha set textures will be exported as Alpha Mode Blend:

![image](https://user-images.githubusercontent.com/3952729/68812683-8949e000-0628-11ea-82a3-f98322e3e2eb.png)

Otherwise if the material is exported improperly we we should see it:
![image](https://user-images.githubusercontent.com/3952729/68812823-d2019900-0628-11ea-9206-0f03867c34f5.png)

Here's the source:
[TestAlphaSourceOpaque.zip](https://github.com/BabylonJS/Exporters/files/3843875/TestAlphaSourceOpaque.zip)

**Comment by Drigax** [comment]
@AndresCH10 and @vpenades, are you still having issues with material transparency settings?

**Comment by vpenades** [comment]
@Drigax yes, the main problem is that both @AndresCH10 and me are working remotely and working with different versions of Max (2019 and 2020) so we're having lots of issues on our own figuring out what's wrong with the scene.

Next week we will do additinal tests to see if we're able to create a proof of concept simple enough to verify the issue.

**Comment by Drigax** [comment]
Sounds good. feel free to reach out if you need any help 🙂

**Comment by Drigax** [comment]
I'm going to close this issue as "unable to reproduce" but if anyone can help provide a consistent repro,  I'll be happy to reopen this

**Comment by vpenades** [comment]
Sorry, we're having lots of issues on our own with 3DSMax, so we're not sure if the problem is on our side or in the exporter.
