### ISSUE TITLE
[Maya] Add support for unit scaling

### ISSUE THREAD

**Issue by Drigax** [BabylonJS/Exporters#694]
Similarly to #481, we should support scene unit scales natively in the Maya exporter.

.Babylon and glTF expect a default unit of meters, so we should take the current unit used in a Maya scene, and convert to Meters during export.

Related to #687, as our global scene scale is used as a workaround for a case where we always export the scene units as Maya's default of centimeters.

**Comment by Drigax** [comment]
Unfortunatly I won't be able to prioritize this issue until I finish working on our Open transcoder work for our 4.1 release timeframe (February)

If anyone is interested in contributing, this shouldn't be terribly difficult to implement, one would just need to be careful as to where to apply the unit scaling.

**Comment by jamesdolan** [comment]
Worth adding to this to also support z-up world coordinates as well as correcting for units.

**Comment by noalak** [comment]
Working on unit scaling atm.

Currently, the 3dsMax version of the support for unit scaling added in #481 is not working.
The further updates of the exporter introduces the "exportParameters" object and has been used everywhere. The scaleFactor retreived from the unit system is ignored. In place the scaleFactor from the Exporter form is used, being applied twice to both a root node and at object level.
**I can fix that too.**

The default system unit for 3dsMax is Inches, not Meters. This means that for all samples and previously exported scenes by users, the positions and vertices'positions of meshes will be updated.
**To ensure retrocompatibility, I suggest to add an export option to "Scale using system unit" (boolean, default false). Ok ?**
The potential issue of non-retrocompatibility has never been brought to light due to the previously mentionned bug nullifying the unit scale factor effects.

Also, the #481 unit scaling is being applied only when exporting to glTF format. **You also want it to be applied when exporting to Babylon format right ?** The unit scaling can be performed earlier, during Babylon process, and will affect glTF process as well.

And finally, applying the scale factor at object level is defintely the way to go and the reason for the "Scale factor" float in Export form is now questionnable. **Do we keep it ?**

**Comment by Drigax** [comment]
I'm not too concerned about retrocompatibility for a bug, if we're scaling the geometry by the form scale factor, then scaling the output scene once more using a scaling node, then this is incorrect behavior and shouldn't be preserved.

I propose that we retain the form scale factor to be used as a scaling node, but use the scene unit scaling for actual scale of the geometry.

Regarding babylon support, the implementation should be similar:

1) the form scaling factor us used only for the scene scaling node

2) DCC unit scale factors are applied to object geometry and transforms

**Comment by noalak** [comment]
> Also please add some evidence that supports that the scaling is being "nullified" rather than being applied twice

I think I was not clear.
- Scaling from unit system is currently non existant.
- Scaling from float in form is applied twice (globally and locally).

**Comment by noalak** [comment]
Opened an issue dedicated to 3dsMax : #746

**Comment by Drigax** [comment]
Fixed via #748
