### ISSUE TITLE
[Max][glTF] Different material colors in exported glTFs

### ISSUE THREAD

**Issue by EtagiBI** [BabylonJS/Exporters#700]
Hello,

I've noticed that some materials change color after export. Here's one of the materials:
![image](https://user-images.githubusercontent.com/20855725/69780860-48c49780-11ce-11ea-9852-9ea082188c83.png)

As you can see above, its color's set to pure white (255-255-255). After export, however, it becomes grayish.
![image](https://user-images.githubusercontent.com/20855725/69781131-0a7ba800-11cf-11ea-80b0-97315c61758d.png)

Model sample:
[New.zip](https://github.com/BabylonJS/Exporters/files/3900148/New.zip)

**Comment by sebavan** [comment]
Hello, you should have an answer shortly but there might be a bit of delay with Thanksgiving :-)

**Comment by EtagiBI** [comment]
What priority does this bug have? Is it included in a road map or something?

**Comment by Drigax** [comment]
Hey @EtagiBI,

I asked @noalak's team to help us fix this bug, currently it is near the top of their priorities. Its currently slated to be fixed by February

**Comment by noalak** [comment]
Yes, stay tuned.

**Comment by noalak** [comment]
Working on it.

**Comment by noalak** [comment]
The reason for the diffuse color factor to be halved is due to following code:

`// Eye Ball correction to limit overall brightness from std to PBR.`
`// This only impacts the factors.`
`var correctedDiffuse = new BabylonColor3(babylonStandardMaterial.diffuse).scale(0.5f);`

I'm not aware of the reason behind this. @Drigax Do you have any documentation explaining the Eye Ball correction ?

Next are results for the glTF Buggy sample.
With the correction:
![Buggy_corrected](https://user-images.githubusercontent.com/20560340/72901613-60ca1a80-3d2a-11ea-8b03-c27b282cb75d.png)

Without the correction:
![Buggy_default](https://user-images.githubusercontent.com/20560340/72901641-6aec1900-3d2a-11ea-8748-8ea07020cf26.png)

Is it something you discussed with Patrick Ryan ?
If you want to hold this behavior, we can add a parameter:
- either a boolean "Eye Ball correction"
- or a float between 0 and 1 "DiffuseColorScaling" being applied to the diffuse color factor

From my point of view the default behavior should be to not apply any correction.

**Comment by Drigax** [comment]
I have no idea why we halve this value, this doesn't seem right at all. We have some known issues with color management throughout the export and rendering process, but I don't think we should have this hack in the source. Please remove this correction.

**Comment by Drigax** [comment]
changes look good, thanks!
