### ISSUE TITLE
Max2Babylon: two JPGs for transparency?

### ISSUE THREAD

**Issue by echadwick-wayfair** [BabylonJS/Exporters#713]
These two setups should enable blended transparency, but only one does.

1. JPG in Base Color+ JPG in Transparency Weight + Transparency Mode: Blend = no transparency. Shouldn't the exporter combine them into a single PNG, and enable transparency?

![screenshot_transp_two-jpgs_v20191209-5](https://user-images.githubusercontent.com/40177036/70725256-0e78f100-1cca-11ea-8b9c-e92fb6b63d2b.jpg)

2. PNG with alpha, in both Base Color and Transparency Weight + Transparency Mode: Blend = transparency. This seems to be working fine.

![screenshot_transp_one-png_v20191209-5](https://user-images.githubusercontent.com/40177036/70725269-13d63b80-1cca-11ea-8110-e5f786586715.jpg)

The two material setups:
![screenshot_Slate Material Editor](https://user-images.githubusercontent.com/40177036/70725285-1afd4980-1cca-11ea-956a-dfb68bdb2688.jpg)

Example files (max, jpgs, png, glbs):
[transp_3dsmax2020_max2babylon20191209-5.zip](https://github.com/BabylonJS/Exporters/files/3956463/transp_3dsmax2020_max2babylon20191209-5.zip)

Max2Babylon 20191209.5
3ds Max 2020.2
Windows 10

Thanks!

**Comment by Drigax** [comment]
Ah, thanks for finding this, looks like this is the offender here:
https://github.com/BabylonJS/Exporters/blob/eb052568de0b0d3a842e5c0e9dbfe9461bd9bfba/3ds%20Max/Max2Babylon/Exporter/BabylonExporter.Texture.cs#L345

Due to that we export materials with a base .jpg as jpg and materials with a base png as png. Not the best implementation. I'm going to make the executive decision to export our output textures after we merge the transparency as PNG, unless I can find good reason to preserve other formats like TIFF or TGA.

I should have a fix for this shortly, but I'm open to revising this fix

**Comment by echadwick-wayfair** [comment]
Thanks!

It would be nice to be able to choose output as JPG or PNG. For example if we want a lossless texture we'd prefer it to stay PNG after export. But if we want small file size, we'd want JPG instead (probably setting a compression amount). Maybe there's a way to specify the output type per input?

This may be a moot point however with KTX on the way https://github.com/KhronosGroup/KTX-Specification/
