### ISSUE TITLE
Maya v20191214.2 is not exporting alpha

### ISSUE THREAD

**Issue by PatrickRyanMS** [BabylonJS/Exporters#720]
# Bug
Wiring up a simple transparency test for an investigation and found that we aren't exporting alpha. Here are the settings:

- Arnold standard surface shader
- diffuse color is wired with a simple png with alpha
- opacity input is wired from the alpha channel of diffuse color
- Babylon node is set to BLEND opacity mode
- mesh attributes for Arnold has opaque disabled
- renders correctly in Arnold with transparency
- blend mode outputs correctly in glTF
- png for diffuse color is written without alpha channel... it is stripped out of original file

[transparencyTest.zip](https://github.com/BabylonJS/Exporters/files/3969951/transparencyTest.zip)

![image](https://user-images.githubusercontent.com/31326855/70939643-819da280-1ffd-11ea-826c-58ca2f75110a.png)

**Comment by Drigax** [comment]
Thanks for reporting this Patrick,

The fix for this looks pretty straightforward:
https://github.com/BabylonJS/Exporters/pull/730

Essentially, the way we query the material node's opacity texture connection does not work for this case, as the Maya API didn't report that the Opacity plug was connected, even though we were driving its components with the alpha channel.

I added some extra checks that let us check a texture plug's children for a connection as well, but I suspect that this may not work well for a case where we drive different opacity channels with different textures. It's a bit of a strange case, however.
