### ISSUE TITLE
Max2Babylon: instanced bitmap = no transparency?

### ISSUE THREAD

**Issue by echadwick-wayfair** [BabylonJS/Exporters#725]
I found some odd behavior when using bitmap instancing in 3ds Max. 
Instancing = wiring a bitmap node output into more than one material input.

![Babylonjs_sandbox](https://user-images.githubusercontent.com/40177036/71849347-d9c94100-309f-11ea-8d49-7699106eaf01.jpg)

![3dsmax_materials](https://user-images.githubusercontent.com/40177036/71849359-de8df500-309f-11ea-8858-ce9ef8e35e70.jpg)

1. If an albedo bitmap is instanced into two materials, one with transparency and one without, then the Alpha channel is discarded upon export.

2. If an albedo bitmap is copied as two inputs, one for each material, then the Alpha channel is properly exported.

This is not a blocker for us, but could prove troublesome later. Also could be confusing for vendors or contractors who export models for us.

[reuse-bitmap-IDs_GLB-files.zip](https://github.com/BabylonJS/Exporters/files/4027857/reuse-bitmap-IDs_GLB-files.zip)

[reuse-bitmap-IDs_3dsMax2020-source-files.zip](https://github.com/BabylonJS/Exporters/files/4027858/reuse-bitmap-IDs_3dsMax2020-source-files.zip)

Max2Babylon 20191220.1
3ds Max 2020.3
Windows 10

**Comment by Drigax** [comment]
@echadwick-wayfair you have a real knack for finding edge cases in our texture export logic 😉

I think this one is a bit complex, currently we export textures as we encounter them per material, and cache which textures were already exported. I assume that may be contributing to this issue, but I'm not totally sure. I'll have to take a look at this first thing tomorrow, but I fear I may want to refactor the current export logic to use multiple passes to first evaluate the textures to be exported from the scene and if we need to process them, then performing the actual processing may help avoid cases like this.

**Comment by echadwick-wayfair** [comment]
Glad to be of assistance :D

**Comment by Drigax** [comment]
Spent some time over the past 2 days investigating this, currently I'm not sure if there is a clean way to handle this.

Currently at export we have 2 materials referencing the same texture source, but the second material requires some additional processing of the texture to add the alpha channel.

At export, we write both textures to disk, using the base color texture name as the final name. In the instanced scene, we end up overwriting the alpha texture with the original texture, and I believe the opposite is happening in the non-instanced scene.

A fix I was working on would involve exporting all permutations of base color texture and transparency texture as separate textures, which would allow for cases where the same instanced base color texture is used in a scene on materials with differenct opacity textures, however this fix leaves a messy edge case in your example, where we have a material that uses the base texture as opaque.

In cases like these, we _should_ optimize our image sources, and find a "suitable" base color image that we can share between the textures to use instead of exporting an additional alpha-less texture, but this seems somewhat messy to implement...

@PatrickRyanMS, have any ideas or hangups regarding this proposal?

**Comment by Drigax** [comment]
I'm going to check in my current fix with these shortcomings, we can always revisit this to improve on it
