### ISSUE TITLE
[Maya] Light rotation and children hierarchy

### ISSUE THREAD

**Issue by noalak** [BabylonJS/Exporters#753]
In Maya, when exporting to Babylon children of lights are not rotated.
This issue is similar to issue #275 in 3dsMax.

Result in glTF (as expected):
![2020-02-10_17h35_16](https://user-images.githubusercontent.com/20560340/74169839-3fbf6000-4c2c-11ea-89ba-02829b861448.png)
The left cone is rotated accordingly to its parent light.

Result in Babylon:
![2020-02-10_17h36_20](https://user-images.githubusercontent.com/20560340/74169888-5665b700-4c2c-11ea-8ef6-b234fe4aec9a.png)

All cones are rotated 90° and the first one ignores its parent light rotation.

Repro files: 
[maya_light_orientation_childToLights.zip](https://github.com/BabylonJS/Exporters/files/4185073/maya_light_orientation_childToLights.zip)

**Comment by Drigax** [comment]
It appears that the hierarchy is preserved in the .babylon file export, I can see that we're linking the cone to the light as a parent:
![image](https://user-images.githubusercontent.com/3952729/75810856-38c5d200-5d40-11ea-8d6c-f6e2d381ca7f.png)

**Comment by Drigax** [comment]
Likewise in Babylon.js, the hierarchy is preserved:
![image](https://user-images.githubusercontent.com/3952729/75819449-8f86d800-5d4f-11ea-85bf-ff8c72bab7b4.png)

The reason why this is not reflected in the scene is due to the in-engine implementation. Lights are represented as Nodes, while the child meshes are represented as NodeTransforms. NodeTransform orientation is not affected by the Node parent. While the fix for this can be made in-engine. I'll also change lights to be serialized in Babylon using a dummyNode as its parent, similarily to how we handle this in glTF export.

**Comment by Drigax** [comment]
After adding the dummy node creation logic, the scene appears to export as expected:

[Export.zip](https://github.com/BabylonJS/Exporters/files/4457966/Export.zip)

**Comment by Drigax** [comment]
Fixed via #800
