### ISSUE TITLE
Instances with unique materials not working in Maya

### ISSUE THREAD

**Issue by catigrasso** [BabylonJS/Exporters#767]
I am trying to export a gltf from Maya 2018 with instanced objects with different materials.

When I export, all instances are assigned the material of the main object, ignoring the individually assigned material for each instance.

The animation of each instance works correctly.

Seems like the same issue was previously happening in 3ds Max: #541

**Comment by Drigax** [comment]
Shame that this got regressed, can you share a repro scene?

**Comment by catigrasso** [comment]
Attached an example Maya scene and the exported gltf
[InstancedBoxesMaterials.zip](https://github.com/BabylonJS/Exporters/files/4222688/InstancedBoxesMaterials.zip)

**Comment by Drigax** [comment]
Thanks, looking at the code I can see that this appears to be caused by how we decipher what is a Master and what is an instance mesh:
https://github.com/BabylonJS/Exporters/blob/b5b8d04b1bdfc9503ebba3d02bfd4fec0a70af18/Maya/Exporter/BabylonExporter.Mesh.cs#L1135-L1151

L1138 checks our list of exported MfnMesh to retrieve the first mesh that has the same path name. Currently we don't check the material properties of either mesh to verify that we should share the same base mesh. I think this can be improved upon as an enhancement. 

I'm currently blocked on the implementation details, however. 
I'm not sure how to properly use the Maya API to retrieve each instance's overriding material.

https://github.com/Drigax/Exporters/blob/d077a5393c6eaaf4916e4f7d088e480adf19f9ff/Maya/Exporter/BabylonExporter.Mesh.cs#L1157-L1169

Currently, reusing the same logic we use to retrieve the material of a master node ends up giving us the same material as the one used for the source mesh, which is not ideal. I'll have to figure out a better way to do this, but currently I'm a bit preoccupied with other work.

**Comment by catigrasso** [comment]
Thanks Nicholas for looking into it.
Found a workaround for the time being, will stay tuned for future
improvements.
