### ISSUE TITLE
maya and material transparency alpha 

### ISSUE THREAD

**Issue by kaisunc** [BabylonJS/Exporters#771]
Using standard lambert/phong material to export, textures with alpha(or transparency ie png) on the diffuse slot always export with diffuseTexture hasAlpha: false. Resulting in incorrect transparency. Is there a reason hasAlpha is defaulted to false?

**Comment by Drigax** [comment]
Sounds like you're running into our export parameter node:
We implemented a hypershade node that's used to save glTF related exporter settings

![image](https://user-images.githubusercontent.com/3952729/75494762-c89b0300-5971-11ea-9c6b-f01080c32d2f.png)

Currently, this is set to export as Opaque (per the glTF default). In order to export transparency properly, this needs to be changed to "Alpha Blend" or "Alpha Test" depending on your needs.
