### ISSUE TITLE
Exporter does not scale properly in 3ds Max 2020

### ISSUE THREAD

**Issue by roy-baker** [BabylonJS/Exporters#789]
I have a basic scene in Max 2020 that contains a box that measures 12" x 24" x 44". The scene unit setup is as 1 Unit = 1.0 Inches. Every time I export the box as GLB it comes out massive on Android AR Scene Viewer. I have tried numerous scale factors but that features has no effect. I have exported as USDZ via Simlab and the scale on the iPhone is perfect in AR. I'm not sure what is going on or how to fix. 
![image](https://user-images.githubusercontent.com/39489978/77109670-b35a4700-69fa-11ea-8fd0-1304f2d56c95.png)
![image](https://user-images.githubusercontent.com/39489978/77109702-ce2cbb80-69fa-11ea-883e-779b6a3ffc15.png)
![image](https://user-images.githubusercontent.com/39489978/77110412-eea94580-69fb-11ea-8eea-f8298ffe2931.png)

**Comment by Drigax** [comment]
I created a simple box in 3dsMax:

[Exporters_789.zip](https://github.com/BabylonJS/Exporters/files/4356993/Exporters_789.zip)

I set the units to inches and exported, the resulting geometry looks accurate (gltf uses meters for units, but whjen converted the bounding box for this mesh's geometry appears to be 12"x44"x24":
![image](https://user-images.githubusercontent.com/3952729/77117026-696b6400-69ee-11ea-91b4-04e3d12839c0.png)

For starters, is there a reason why your world origin is near SIGNED_INT_MAX? I wouldn't be surprised if this affects the geometry or calculated world matrix of the object, since we derive all this from the world transform, and I believe that Max still uses single precision floating point, so we could be losing precision due to this.

Secondly, does this only occur when using inches as your world unit? we have to manually convert whatever unit the scene is set in to meters; I'd assume that this is not particularly related to the scene unit type, but I may be wrong.

Thirdly, can you share your output glb and a sample max scene that reproduces this issue?

**Comment by roy-baker** [comment]
Here is the Max file and GLB.

Here is the test site:
http://virtualtour.hermanmiller.com/ar/

[box.zip](https://github.com/BabylonJS/Exporters/files/4357082/box.zip)

**Comment by Drigax** [comment]
Thanks, looking at the scene I can see:
![image](https://user-images.githubusercontent.com/3952729/77121467-7e4cf500-69f8-11ea-9222-d57fc3698152.png)
where we have the scene globally scaled by a factor of 0.01. Lets remove this global scaling to make sure we're staying true to the in-Max scene.

If I remove this global scene scaling the resulting gltf appears properly constructed:

![image](https://user-images.githubusercontent.com/3952729/77121911-8d807280-69f9-11ea-8eba-e679cd3f1169.png)


Calculating the exported bounding box values we get a model with dimensions:
X = 0.301625091m -> 11.875003612"
Y = 1.122730727m -> 44.201997125"
Z = 0.606425047m -> 23.875001837"

This looks inline with your mesh in engine and your expected dimensions.

I'd suggest checking the scaling of the rest of your objects used in your scene.

**Comment by roy-baker** [comment]
I set the scale factor to 1, moved the box to the center of the world and re-exported. The box is still huge when viewed in the AR scene viewer mode on Android. I am using the  <model-viewer src="assets/gltf_export/box.glb"... code to publish the glb. Have you tried the Box on an Android in AR versus full screen mode? How are you determining the size as true? I'm starting to wonder if the issue in the the web code somewhere

<script src="https://cdn.babylonjs.com/viewer/babylon.viewer.js"></script>
<model-viewer src="assets/gltf_export/box.glb" alt="Box" auto-rotate="" shadow-intensity="1" shadow-softness="1"
              camera-controls="" background-color="#ffffff" ar="" magic-leap="" unstable-webxr=""
				  ios-src="assets/USDZ_export/box.usdz">
    </model-viewer>
 


<script type="module"
    src="model-viewer.js">
</script>


<script nomodule
    src="model-viewer-legacy.js">
</script>

**Comment by roy-baker** [comment]
I solved it. 

I stripped out the following local file references to the scripts I downloaded to my site: 
<script type="module"
    src="model-viewer.js">
<script nomodule
    src="model-viewer-legacy.js">
</script>-->

 and reset it to 
<script type="module" src="https://unpkg.com/@google/model-viewer/dist/model-viewer.js"></script>
<script nomodule src="https://unpkg.com/@google/model-viewer/dist/model-viewer-legacy.js"></script>

and now the scaling is correct,
