### ISSUE TITLE
Feature Request - Export clones

### ISSUE THREAD

**Issue by saidmoya12** [BabylonJS/Exporters#835]
It's possible export clones from 3dsmax to allow instances with different material?

https://doc.babylonjs.com/how_to/optimizing_your_scene

> If sharing the same material is a problem, you can then think about using clones which share the same geometry with mesh.clone("newName")

Like - **Export instances as clones**

Thanks!

**Comment by Drigax** [comment]
I believe we already support instances with different materials, no?

**Comment by saidmoya12** [comment]
Thanks for your answer but no

BabylonJs doesn't support different material on instances
https://www.babylonjs.com.cn/how_to/how_to_use_instances.html

> **Each instance has the same material as the root mesh. They can only vary on the following properties:**
> position
> rotation
> rotationQuaternion
> setPivotMatrix
> scaling

Checking the link [optimizing your scene](https://doc.babylonjs.com/how_to/optimizing_your_scene)

> **Reducing draw calls**
>
> As soon as you can please use instances as they are drawn with one single draw call.
>
> If sharing the same material is a problem, you can then think about using clones which share the same geometry with **mesh.clone("newName")**
>
> One remark regarding instances: If one of the instances has a world matrix with a different determinant (eg. one instance has a negative scale where others don't), babylon.js will be forced to remove the back face culling from their material.

This is the problem when for example in my case I need export 500 meshes (same geometry) with different materials

So I suggest an option to export instances as clones or a babylon object property to do this :(

I appreciate any idea

**Comment by deltakosh** [comment]
Would you be ok to do a PR for it?

**Comment by pandaGaume** [comment]
One question is about the logic behind these clones creation. Actual behavior is based on identify already exported node with the same mesh and same material to create a Babylon instance. No matter the order of arrival during the export process. So 

1. a 3DS "original" node could become a Babylon instance depending the order of export. 
2. an 3DS instance (or reference) could become a Babylon copy if it NOT share the same material as the "original".
3. an 3DS instance (or reference) could become an Babylon instance of another Babylon instance if sharing the same .material. This last point may drive to unconsistent behaviour if we have 3DS reference instead of 3DS instance
 
All this points are breaking the rules of the original scene graph and object dependencies, and i beleive we might be clear and consistent about the original, copy , instance and reference. 

Optimizing geometry using Babylon cloning is ONE thing.

Keeping the scene consistent is another one and implie more changes into the code. 
So final question is  : _We maybe address this last point in another issue_ ??

**Comment by pandaGaume** [comment]
FYI, i move onto the path to create BabylonGeometries and BabylonVertexData, adding reference to geometrieID within BabylonMesh.
Adding a set of geometries to the scene give us the possibility to write a very simple clone extensions such
```
   public static BabylonMesh Clone(this BabylonMesh mesh, BabylonScene scene)
        {
            string gid = mesh.geometryId;
            if (gid == null)
            {
                // we may create the geometry into the scene
                gid = mesh.id;
                if (!scene.geometries.Contains(gid))
                {
                    scene.geometries.Add(new BabylonVertexData(gid, mesh));
                }
                // and update the mesh.
                mesh.geometryId = gid;
                mesh.ClearLocalGeometry();
            }

            BabylonMesh newMesh = new BabylonMesh() {
                materialId = mesh.materialId,
                geometryId = gid
            };
            return newMesh;
        } 
```
This is ok for Babylon File Format, as i follow the documentation..

from this point, next step is to update the Babylon2GLTF in order to use the geometryId instead as embedded arrays (for the purpose i declare a common interface used by BabylonVertexData and BabylonMesh).

Keep you posted.

**Comment by pandaGaume** [comment]
Ok Guy's, i'm near to close it. I have a fully functional version which optimize the geometry instance and references using clone strategy, for both babylon and GLTF. However, this is a kind of core modifications and it has to be used carefully and well tested against many scenarii before final validation.

**Comment by pandaGaume** [comment]
This is the reference test scene
[instances.zip](https://github.com/BabylonJS/Exporters/files/5747912/instances.zip)
and result as cloned and not-cloned
[test_clone.zip](https://github.com/BabylonJS/Exporters/files/5747918/test_clone.zip)

**Comment by deepkolos** [comment]
maya have the same issue, please add this feature to maya's gltf exporter
