### ISSUE TITLE
3dsmax - Unknown system error during export to glb

### ISSUE THREAD

**Issue by ukito-pl** [BabylonJS/Exporters#879]
**Description:**
Unkown exception occurs during model export from max scene to glb file. It happens only on specific models, some models do convert, some don't. I attached a zip file with test model that doesn't export to glb:  [test_model.zip](https://github.com/BabylonJS/Exporters/files/5414492/test_model.zip)
Interesting thing I noticed is that sometimes exporting via user interface results in successfull export while exporting the same file using maxscript run with 3dsmaxbatch results in unknown system error.

Here is error log from maxscript listener:
> -- MAXScript ExecuteMAXScriptScript Exception:
> -- Unknown system exception
> -- MAXScript callstack:
> --	thread data: threadID:136
> --	[stack level: 0]
> --	In top-level

Script I used to export model with maxscript:
`Assembly = dotNetClass "System.Reflection.Assembly"`
`Assembly.loadfrom "C:\Program Files\Autodesk\3ds Max 2021\bin\assemblies\Max2Babylon.dll"`
`maxScriptManager = dotNetObject "Max2Babylon.MaxScriptManager"`
`param = maxScriptManager.InitParameters "G:\\test.glb"`
`param.exportTextures = true`
`param.exportMaterials = true`
`param.enableKHRMaterialsUnlit = true`
`param.enableKHRTextureTransform = true`
`maxScriptManager.Export param true`

At first I thought that it might be caused by not enough free memory, but memory usage during export does not exceed available memory resources. 

**How to reproduce**
Download attached model and run export either from 3dsmax UI or from command line using 3dsmaxbatch with above script, for example:
`3dsmaxbatch above_script.ms -sceneFile "test_model.max" -dm on -listenerLog log.txt -log maxlog.txt -v 5`

**PC Specs**
Windows 10 1903
Processor: intel i5 6500 3,2GHz
Ram: 16 GB
Graphic card: GF 1060 6GB

**Versions**
3dsmax 2021, version: 23.0.0.915
Babylon exporter versoin: 20201012.1

**Comment by pandaGaume** [comment]
It's something append with the material of the houses gutters model... the only thing i noticed is that Babylon property (MaxNumberOfLight) were set to 100 instead of 4 on "rinna pion" material, meaning that something changed during edition OR max property file was corrupted.
I'm still not able to find the reason and get a clear explanation of the AccessViolationException (which is commonly due to wrong pointer value in the underlying unmanaged code) occuring when exporting this particular material.
you may try to change/redo the material on the gutter then you might be able to export the model. In the mean time we will try to find the reason of this behavior.

**Comment by ukito-pl** [comment]
Thanks for reply :) 
It seems really weird because in my file I have following setting for "rynna pion" material:
![image](https://user-images.githubusercontent.com/19152578/96841700-65079d80-144c-11eb-8d49-305b5381c03c.png)
As you can see in "node" view it says that maxSimultaneousLights is '10653...' and in normal view it shows 4, maxscript also shows 4. I cannot change the value on node view. When I try to do it, it always defualts to '10653...', but in the same time it changes the value in normal view to 100(maximum range of the field, from maxscript it shows '10653...')

Changing the "rynna pion" material properties did not help, but assigning new material instead of the old one does the trick.
Unfortunately it is not a solution I am looking for because I can't see the reason why this material doesn't work and others do. Is there anything else I can check? Maybe there is some problem with assingning babylon properties at load? Because originally model was created in 3dsmax without babylon plugin.

Another thing I noticed:
If I change blend mode on material for windows (material "szklo") to 'opaque' instead of 'blend' it exports correctly! It just seems really random at this point.

**Comment by pandaGaume** [comment]
The good new is we find a work arround for the moment. What your noticed is typically a corrupted pointer somewhere in unmanaged code from Max SDK, which create erratic behavior, even on unrelated topic. We might find where the leak is first.. I will continue to investigate.

**Comment by ukito-pl** [comment]
Ok, thank you, I will wait until you locate the issue :)

**Comment by renjianqiang** [comment]
I happen to have the same problem these days, and i found these code cause the problem:
```
//3ds Max\Max2Babylon\Exporter\BabylonExporter.Material.cs

// Add babylon attributes
//AddStandardBabylonAttributes(materialNode.MaterialName, babylonMaterial);
```
We just need to comment this line of code, and will fix the crash problem. Here is the modified plug-in, hope this helps.
[max2019.zip](https://github.com/BabylonJS/Exporters/files/5429129/max2019.zip)

Then i want to talk about why.  Here is the key code:
```
// Add babylon attributes
AddStandardBabylonAttributes(materialNode.MaterialName, babylonMaterial);  

if (babylonAttributesContainer != null)
{
    RaiseVerbose("Babylon Attributes of " + materialNode.MaterialName, 2);

    // Common attributes
    ExportCommonBabylonAttributes(babylonAttributesContainer, babylonMaterial);
```
Firstly, i think the `AddStandardBabylonAttributes`  function does nothing, because of the `AddCallbacks()` function has register a callback to add Babylon Attributes when import or edit the models, So we don't need this function do same thing again.

Secondly, i think the exception thrown from `ExportCommonBabylonAttributes` is caused by `AddStandardBabylonAttributes`. Consider this case, `AddStandardBabylonAttributes` excuted some max scripts, and have not free some resource, then `ExportCommonBabylonAttributes` query some property from max,  then the exception thrown. Above is my  guesses and i'm not sure if this is right. @pandaGaume

I would be very grateful if someone can prove my answer or  point out problem in my answer.

**Comment by pandaGaume** [comment]
Hi @renjianqiang, we are looking actually on the Script Attribute subject, which is in cause on few crashes issues.
