### ISSUE TITLE
Some glTF files in the Maya folder have validation errors

### ISSUE THREAD

**Issue by cx20** [BabylonJS/Exporters#943]
I tried to display the following sample model on [BabylonJS Sandbox](https://sandbox.babylonjs.com/).
https://github.com/BabylonJS/Exporters/tree/master/Maya/Samples/glTF%202.0/T-Rex

However, it seems that many validation errors are occurring.
![image](https://user-images.githubusercontent.com/1833979/111892621-67444700-8a40-11eb-8cfe-63df68e7bb5b.png)

Perhaps the skinning animation model is in error.

It is hoped that the sample error will be resolved.

**Comment by pandaGaume** [comment]
Hi guy's,
Thank's to spot this. Actually the exporter do it a way better, but still few validation issues about normalized weight (due to rounding issue into serialization). This is on our todo list.
![image](https://user-images.githubusercontent.com/22658224/111967614-8a323200-8af8-11eb-90cd-3b892bc57ca2.png)

**Comment by cx20** [comment]
@pandaGaume Thank you for merging the new model. 
However, it seems that old models are still mixed. It's confusing, so I think it's better to remove the old model (`trex_running.*`) and textures (`*.jpg`).

Probably the red part is the old model and texture. (It seems that the old model uses `jpg` for the texture and the new model uses `png`.)
![image](https://user-images.githubusercontent.com/1833979/120838559-e6a6d880-c5a2-11eb-9e8b-e7d9425d1b4c.png)
