### ISSUE TITLE
3ds max 2022 version?

### ISSUE THREAD

**Issue by tvortsa** [BabylonJS/Exporters#948]
When here will be exporter for 3DS Max 2022 version ?

**Comment by pandaGaume** [comment]
Let me check with the team. We will come back to you soon.

**Comment by AlviseDandolo** [comment]
Any date on this? Love your work!

**Comment by pandaGaume** [comment]
Hey guy's,
There is a lot of sdk update with the 2022, so we do not know yet a long it might take. We have a couple of issue to take care about before this.

**Comment by rogergrytdal** [comment]
Thanks for the update. Just asking for a hint, because all my coworkers have updated to Max 2022 along time ago. I using the exporter on daily basis at work and cannot update 😂😭



ROGER GRYTDAL

FutureOn Corporation
Makers of FieldAp - Field Development Software
m +47 952 15 261

3D CONTENT MANAGER/ENGINEER

e ***@***.******@***.***>

w www.futureon.com<https://urldefense.com/v3/__http:/www.futureon.com/__;!!AxreNA!j-uRpzcsj7F7Uxof97HRIXvivQydwfNS4YD9XuQ2-fjsjkIH6gkX1RcR9ThXCjTs$>



________________________________
Fra: Guillaume Pelletier ***@***.***>
Sendt: Wednesday, July 14, 2021 5:21:50 PM
Til: BabylonJS/Exporters ***@***.***>
Kopi: roger ***@***.***>; Comment ***@***.***>
Emne: Re: [BabylonJS/Exporters] 3ds max 2022 version? (#948)


Hey guy's,
There is a lot of sdk update with the 2022, so we do not know yet a long it might take. We have a couple of issue to take care about before this.

**Comment by AlviseDandolo** [comment]
Same here, I'll have to stick to 2021 for the time being. I'll keep an eye on the update notifications.

**Comment by pandaGaume** [comment]
Hey Guy's,
I understand your point. This is an open source project, and I have also my own priorities with my regular job.
So any helps are welcome.

**Comment by rogergrytdal** [comment]
@pandaGaume I understand, no critic. You guys doing a great job!!

**Comment by pandaGaume** [comment]
Here the dll on very first preview. I need your help to test with your 3d models and come back to me with a list of issues. As i told you, they was a LOT of change into the new Autodesk SDK...
[2022 bin.zip](https://github.com/BabylonJS/Exporters/files/6824063/2022.bin.zip)
Note this is not officially supported yet, only the very first milestone.

**Comment by pandaGaume** [comment]
@bghgary & @sebavan could you have a look on azure pipeline to compile the 2022 project, or giving me the directions & rights to do it (keeping in mind we MUST use Framework 4.8 instead as 4.7).
G.

**Comment by pandaGaume** [comment]
Still installer issue. Keep u posted.
