### ISSUE TITLE
Max2Babylon: why warn for disabled KHR_texture_transform if no transforms?

### ISSUE THREAD

**Issue by echadwick-wayfair** [BabylonJS/Exporters#986]
Is there a reason why the exporter warns about a disabled KHR_texture_transform when the bitmaps have no transforms applied (default behavior for bitmaps)?

![image](https://user-images.githubusercontent.com/40177036/126172784-3bca01a3-a5a7-4dcf-8884-26f11f759894.png)

3ds Max 2020.3
Max2Babylon v20210624.1

Thanks!

**Comment by pandaGaume** [comment]
Hello,
This not suppose to.. 
Along with this, the message is clearly duplicated.
Could you share a repro with us ??
Thank's

**Comment by echadwick-wayfair** [comment]
1. Start 3ds Max.
2. Make a Plane primitive.
3. Make a Physical Material.
4. Add a Bitmap node, connected to Base Color Map input.
5. Load any bitmap into the node.
6. Apply the material to the Plane.
7. Babylon File Exporter
8. Output format: gltf
9. Model path: c:\temp\test.gltf
10. Texture path: c:\temp
11. Export.

[test.zip](https://github.com/BabylonJS/Exporters/files/6843018/test.zip)

**Comment by pandaGaume** [comment]
After a quick look, this is due to the fact we flip the Y texture, then the test for ScaleV against 1 is failed with a value of -1
I beleive this is for historical reason, because we first flip the Y of the image for babylon format. 
So because we are on GLTF exporter part, we may test
`!(babylonTexture.vScale == -1)`
instead as 
`!(babylonTexture.vScale == 1)`
I'll make a PR on the topic.
